Repository Nexus-Mods/NexusMods.App, pull requests merged in 2023-08, with the labels that each got.

#500 Added: Fully Featured support for Download Suspend & Resume (fixes #255 fixes #480)
  src/Networking/NexusMods.Networking.Downloaders/DownloadService.cs
  src/Networking/NexusMods.Networking.Downloaders/Interfaces/IDownloadService.cs
  src/Networking/NexusMods.Networking.Downloaders/Interfaces/IDownloadTask.cs
  src/Networking/NexusMods.Networking.Downloaders/Interfaces/Traits/IHaveGameDomain.cs
  src/Networking/NexusMods.Networking.Downloaders/Interfaces/Traits/IHaveTypeSpecificState.cs
  src/Networking/NexusMods.Networking.Downloaders/NexusMods.Networking.Downloaders.csproj
  src/Networking/NexusMods.Networking.Downloaders/NxmDownloadTask.cs
  src/Networking/NexusMods.Networking.Downloaders/Services.cs
  src/Networking/NexusMods.Networking.Downloaders/Tasks/HttpDownloadTask.cs
  src/Networking/NexusMods.Networking.Downloaders/Tasks/NxmDownloadTask.cs
  src/Networking/NexusMods.Networking.Downloaders/Tasks/State/DownloaderState.cs
  src/Networking/NexusMods.Networking.Downloaders/Tasks/State/HttpDownloadState.cs
  src/Networking/NexusMods.Networking.Downloaders/Tasks/State/ITypeSpecificState.cs
  src/Networking/NexusMods.Networking.Downloaders/Tasks/State/NxmDownloadState.cs
  src/Networking/NexusMods.Networking.Downloaders/TypeFinder.cs
  src/Networking/NexusMods.Networking.HttpDownloader/AdvancedHttpDownloader.cs
  src/Networking/NexusMods.Networking.HttpDownloader/HttpDownloaderState.cs
  src/Networking/NexusMods.Networking.HttpDownloader/SimpleHttpDownloader.cs
  src/NexusMods.App.UI/Controls/Buttons/RoundedButton/RoundedButton.axaml
  src/NexusMods.App.UI/Controls/Spine/Buttons/Icon/IconButton.axaml
  src/NexusMods.App.UI/RightContent/DownloadGrid/Columns/DownloadStatus/DownloadStatusDesignViewModel.cs
  src/NexusMods.App.UI/RightContent/DownloadGrid/Columns/DownloadStatus/DownloadStatusView.axaml
  src/NexusMods.App.UI/RightContent/DownloadGrid/Columns/DownloadStatus/DownloadStatusView.axaml.cs
  src/NexusMods.App.UI/RightContent/DownloadGrid/Columns/DownloadStatus/DownloadStatusViewModel.cs
  src/NexusMods.App.UI/RightContent/DownloadGrid/Columns/DownloadStatus/IDownloadStatusViewModel.cs
  src/NexusMods.App.UI/RightContent/Downloads/IInProgressViewModel.cs
  src/NexusMods.App.UI/RightContent/Downloads/InProgressCommonViewModel.cs
  src/NexusMods.App.UI/RightContent/Downloads/InProgressView.axaml.cs
  src/NexusMods.App.UI/RightContent/Downloads/InProgressViewModel.cs
  src/NexusMods.App.UI/RightContent/Downloads/ViewModels/DownloadTaskDesignViewModel.cs
  src/NexusMods.App.UI/RightContent/Downloads/ViewModels/DownloadTaskViewModel.cs
  src/NexusMods.App.UI/RightContent/Downloads/ViewModels/IDownloadTaskViewModel.cs
  src/NexusMods.App.UI/Services.cs
  src/NexusMods.App.UI/Windows/MainWindowViewModel.cs
  src/NexusMods.App/Listeners/NxmRpcListener.cs
  src/NexusMods.DataModel/Abstractions/EntityCategory.cs
  tests/Networking/NexusMods.Networking.Downloaders.Tests/DownloadServiceDataStoreTests.cs
  tests/Networking/NexusMods.Networking.Downloaders.Tests/DownloadServiceTests.cs
  tests/Networking/NexusMods.Networking.Downloaders.Tests/HttpDownloadTaskTests.cs
  tests/Networking/NexusMods.Networking.Downloaders.Tests/NexusMods.Networking.Downloaders.Tests.csproj
  tests/Networking/NexusMods.Networking.Downloaders.Tests/NxmDownloadTaskTests.cs
  tests/Networking/NexusMods.Networking.Downloaders.Tests/Serialization/DownloaderStateTests.cs
  tests/Networking/NexusMods.Networking.Downloaders.Tests/Startup.cs
  tests/Networking/NexusMods.Networking.Downloaders.Tests/Tasks/DownloadTasksCommon.cs
  tests/Networking/NexusMods.Networking.Downloaders.Tests/Tasks/HttpDownloadTaskTests.cs
  tests/Networking/NexusMods.Networking.Downloaders.Tests/Tasks/NxmDownloadTaskTests.cs
  tests/Networking/NexusMods.Networking.Downloaders.Tests/TypeFinder.cs
  tests/Networking/NexusMods.Networking.Downloaders.Tests/xunit.runner.json
Labels: complexity-large, meta-improvement, area-ui

#538 Replace Moq with NSubstitute
  Directory.Packages.props
  tests/Directory.Build.props
  tests/Networking/NexusMods.Networking.Downloaders.Tests/Serialization/DownloaderStateTests.cs
  tests/Networking/NexusMods.Networking.Downloaders.Tests/Tasks/DownloadTasksCommon.cs
  tests/Networking/NexusMods.Networking.Downloaders.Tests/Tasks/HttpDownloadTaskTests.cs
  tests/Networking/NexusMods.Networking.Downloaders.Tests/Tasks/NxmDownloadTaskTests.cs
  tests/Networking/NexusMods.Networking.NexusWebApi.Tests/MockHttpMessageHandler.cs
  tests/Networking/NexusMods.Networking.NexusWebApi.Tests/OAuth2MessageFactoryTests.cs
  tests/Networking/NexusMods.Networking.NexusWebApi.Tests/OAuthTests.cs
  tests/Networking/NexusMods.Networking.NexusWebApi.Tests/Startup.cs
  tests/NexusMods.CLI.Tests/VerbTests/ProtocolInvocationTests.cs
  tests/NexusMods.Common.Tests/OSInteropTests.cs
  tests/NexusMods.DataModel.RateLimiting.Tests/JobThroughputTests.cs
  tests/NexusMods.DataModel.Tests/LoadoutSynchronizerTests/ApplyLoadoutTests.cs
  tests/NexusMods.UI.Tests/RightContent/Downloads/ViewModels/DownloadTaskViewModelTests.cs
Labels: area-dependencies

#555 Add Working Directory to .nxm Handler & Remove Default Host Builder (fixes #513)
  src/NexusMods.App/Program.cs
  src/NexusMods.Common/ProtocolRegistration/IProtocolRegistration.cs
  src/NexusMods.Common/ProtocolRegistration/ProtocolRegistrationLinux.cs
  src/NexusMods.Common/ProtocolRegistration/ProtocolRegistrationWindows.cs
  tests/NexusMods.DataModel.Tests/Harness/ADataModelTest.cs
Labels: complexity-small, type-spike, meta-performance, os-windows, os-linux

#551 Upgrade GameFinder to 3.2.2
  Directory.Packages.props
Labels: area-dependencies
