Repository Nexus-Mods/NexusMods.App, pull requests merged in 2023-04, with the labels that each got.

#251 Make AbsolutePath factory functions internal
  src/ArchiveManagement/NexusMods.FileExtractor/TemporaryFileManagerEx.cs
  src/NexusMods.Paths/AbsolutePath.cs
Labels: small, improvement :chart_with_upwards_trend:

#246 [Feedback Requested] Added: Draft Documentation for SkyrimSE
  docs/games/00001-SkyrimSE.md
Labels: documentation :paperclip:, small

#261 Fixed: Double Import of Directory.Build.props (fixes #260)
  tests/Games/NexusMods.Games.BethesdaGameStudios.Tests/NexusMods.Games.BethesdaGameStudios.Tests.csproj
  tests/Games/NexusMods.Games.DarkestDungeon.Tests/NexusMods.Games.DarkestDungeon.Tests.csproj
  tests/Games/NexusMods.Games.FOMOD.Tests/NexusMods.Games.FOMOD.Tests.csproj
  tests/Games/NexusMods.Games.RedEngine.Tests/NexusMods.Games.RedEngine.Tests.csproj
Labels: bug :bug:, small

#259 Refactor HashRelativePath for Simplification and Efficiency (fixes #210)
  src/NexusMods.DataModel/ArchiveManager.cs
  src/NexusMods.DataModel/Loadouts/Markers/LoadoutMarker.cs
  src/NexusMods.Hashing.xxHash64/HashRelativePath.cs
  src/NexusMods.Paths/Extension.cs
  tests/NexusMods.DataModel.Tests/DataStoreTests.cs
Labels: small

#278 Fix table rendering with Sepctre
  src/NexusMods.App/CLI/Renderers/Spectre.cs
Labels: bug :bug:, small

#280 Fix trace logging
  src/NexusMods.App/Program.cs
Labels: bug :bug:, small

#265 Add `GameStore` to `GameInstallation`
  src/Games/NexusMods.Games.BethesdaGameStudios/SkyrimSpecialEdition.cs
  src/Games/NexusMods.Games.DarkestDungeon/DarkestDungeon.cs
  src/Games/NexusMods.Games.RedEngine/Cyberpunk2077.cs
  src/Games/NexusMods.Games.Reshade/ReshadePresetInstaller.cs
  src/Games/NexusMods.Games.Sifu/Sifu.cs
  src/Games/NexusMods.Games.StardewValley/StardewValley.cs
  src/NexusMods.CLI/Verbs/ListGames.cs
  src/NexusMods.DataModel/Games/AGame.cs
  src/NexusMods.DataModel/Games/GameInstallation.cs
  src/NexusMods.DataModel/Games/GameLocatorResult.cs
  src/NexusMods.DataModel/Games/GameStore.cs
  src/NexusMods.DataModel/Games/RunGameTool.cs
  src/NexusMods.DataModel/JsonConverters/GameInstallationConverter.cs
  src/NexusMods.StandardGameLocators/AGameLocator.cs
  src/NexusMods.StandardGameLocators/EADesktopLocator.cs
  src/NexusMods.StandardGameLocators/EpicLocator.cs
  src/NexusMods.StandardGameLocators/GogLocator.cs
  src/NexusMods.StandardGameLocators/OriginLocator.cs
  src/NexusMods.StandardGameLocators/SteamLocator.cs
  tests/NexusMods.StandardGameLocators.TestHelpers/StubbedGames/StubbedGame.cs
  tests/NexusMods.StandardGameLocators.TestHelpers/UniversalStubbedGameLocator.cs
  tests/NexusMods.StandardGameLocators.Tests/BasicTests.cs
  tests/NexusMods.UI.Tests/NexusMods.UI.Tests.csproj
  tests/NexusMods.UI.Tests/Resources/cyberpunk2077.1.61.zip
  tests/NexusMods.UI.Tests/SpineTests.cs
Labels: game support :video_game:, improvement :chart_with_upwards_trend:

#296 High performance logging
  benchmarks/NexusMods.Benchmarks/Benchmarks/HighPerformanceLogging.cs
  benchmarks/NexusMods.Benchmarks/Benchmarks/IdToString.cs
  src/NexusMods.App.UI/HighPerformanceLogging.cs
  src/NexusMods.App.UI/InjectedViewLocator.cs
  src/NexusMods.DataModel/Abstractions/EntityCategory.cs
  src/NexusMods.DataModel/Abstractions/Ids/AId.cs
  src/NexusMods.DataModel/HighPerformanceLogging.cs
  src/NexusMods.DataModel/Interprocess/SqliteIPC.cs
  src/NexusMods.DataModel/NexusMods.DataModel.csproj
  src/NexusMods.DataModel/SqliteDataStore.cs
Labels: small, improvement :chart_with_upwards_trend:, performance ⚡
