Repository Nexus-Mods/NexusMods.App, pull requests merged in 2023-07, with the labels that each got.

#365 Windows and Wine path fixes
  src/NexusMods.Paths/FileSystemAbstraction/BaseFileSystem.cs
  src/NexusMods.Paths/FileSystemAbstraction/IFileSystem.cs
  src/NexusMods.Paths/OSInformation.cs
  src/NexusMods.Paths/Utilities/PathHelpers.cs
  tests/NexusMods.Paths.Tests/FileSystem/BaseFileSystemTests.cs
  tests/NexusMods.Paths.Tests/PathHelperTests.cs
Labels: meta-bug, os-windows, os-linux

#440 Added: A bunch of .nx related fixes. (fixes #410)
  src/ArchiveManagement/NexusMods.FileExtractor/NexusMods.FileExtractor.csproj
  src/NexusMods.Common/NexusMods.Common.csproj
  src/NexusMods.DataModel/NexusMods.DataModel.csproj
  src/NexusMods.DataModel/NxArchiveManager.cs
  src/NexusMods.DataModel/Services.cs
  src/NexusMods.DataModel/ZipArchiveManager.cs
Labels: meta-bug

#441 Remove Accidental Inclusion of Project from Testing
  src/NexusMods.DataModel/NexusMods.DataModel.csproj
Labels: meta-bug

#445 Fix broken version parsing for SMAPI Manifests
  src/Games/NexusMods.Games.StardewValley/Analyzers/SMAPIManifestAnalyzer.cs
  src/Games/NexusMods.Games.StardewValley/Emitters/001_MissingDependencies.cs
  src/Games/NexusMods.Games.StardewValley/Installers/SMAPIModInstaller.cs
  src/Games/NexusMods.Games.StardewValley/Models/SMAPIManifest.cs
  src/Games/NexusMods.Games.StardewValley/Models/SMAPIManifestDependency.cs
  src/Games/NexusMods.Games.StardewValley/Models/SMAPIVersion.cs
  src/Games/NexusMods.Games.StardewValley/NexusMods.Games.StardewValley.csproj
  src/Games/NexusMods.Games.StardewValley/TypeFinder.cs
  tests/Games/NexusMods.Games.StardewValley.Tests/Analyzers/SMAPIManifestAnalyzerTests.cs
  tests/Games/NexusMods.Games.StardewValley.Tests/Emitters/001_MissingDependencyTests.cs
  tests/Games/NexusMods.Games.StardewValley.Tests/Models/SMAPIVersionTests.cs
  tests/Games/NexusMods.Games.StardewValley.Tests/TestHelper.cs
Labels: area-game-support

#482 Upgrade Avalonia to 11.0.1
  Directory.Packages.props
Labels: area-dependencies

#484 Refactored content sending method and updated tests
  src/Networking/NexusMods.Networking.HttpDownloader/AdvancedHttpDownloader.cs
  src/NexusMods.CLI/Services.cs
  tests/Games/NexusMods.Games.TestFramework/DependencyInjectionHelper.cs
  tests/Games/NexusMods.Games.TestFramework/TestModDownloader.cs
  tests/Networking/NexusMods.Networking.HttpDownloader.Tests/AdvancedHttpDownloaderTests.cs
  tests/Networking/NexusMods.Networking.HttpDownloader.Tests/LocalHttpServer.cs
  tests/Networking/NexusMods.Networking.HttpDownloader.Tests/Startup.cs
  tests/NexusMods.DataModel.Tests/Startup.cs
Labels: status-dont-merge
