Repository Nexus-Mods/NexusMods.App, pull requests merged in 2023-03, with the labels that each got.

#145 Add `.gitattributes` file
  .gitattributes
  NexusMods.App.sln
Labels: small, improvement :chart_with_upwards_trend:

#147 Small codecov fixes
  .github/workflows/validate-codecov.yaml
  codecov.yaml
Labels: small, improvement :chart_with_upwards_trend:

#146 Add `.editorconfig` file
  .editorconfig
  NexusMods.App.sln
Labels: small, improvement :chart_with_upwards_trend:

#156 Upload build artifacts to GH with each build
  .github/workflows/git-builds.yaml
  scripts/build-linux-x64.sh
  scripts/build-win-x64.ps1
  src/NexusMods.App.UI/NexusMods.App.UI.csproj
Labels: small

#153 Use Copy Target instead of None for Resources
  tests/Games/NexusMods.Games.BethesdaGameStudios.Tests/NexusMods.Games.BethesdaGameStudios.Tests.csproj
  tests/Games/NexusMods.Games.RedEngine.Tests/NexusMods.Games.RedEngine.Tests.csproj
  tests/NexusMods.CLI.Tests/NexusMods.CLI.Tests.csproj
  tests/NexusMods.DataModel.Tests/NexusMods.DataModel.Tests.csproj
  tests/NexusMods.FileExtractor.Tests/NexusMods.FileExtractor.Tests.csproj
Labels: small

#161 Use CliWrap in NexusMods.Common
  src/Networking/NexusMods.Networking.NexusWebApi/OAuth.cs
  src/NexusMods.Common/IProcessFactory.cs
  src/NexusMods.Common/NexusMods.Common.csproj
  src/NexusMods.Common/OSInterop/IOSInterop.cs
  src/NexusMods.Common/OSInterop/OSInteropLinux.cs
  src/NexusMods.Common/OSInterop/OSInteropOSX.cs
  src/NexusMods.Common/OSInterop/OSInteropWindows.cs
  src/NexusMods.Common/ProcessFactory.cs
  src/NexusMods.Common/Services.cs
  src/NexusMods.CommonTests/OSInteropTests.cs
  tests/Networking/NexusMods.Networking.NexusWebApi.Tests/OAuth2MessageFactoryTests.cs
  tests/Networking/NexusMods.Networking.NexusWebApi.Tests/OAuthTests.cs
  tests/Networking/NexusMods.Networking.NexusWebApi.Tests/Startup.cs
Labels: improvement :chart_with_upwards_trend:

#173 Nullable warnings as errors
  .editorconfig
  NexusMods.App.sln
  NullableErrors.Build.props
  src/ArchiveManagement/NexusMods.FileExtractor/NexusMods.FileExtractor.csproj
  src/Games/NexusMods.Games.BethesdaGameStudios/NexusMods.Games.BethesdaGameStudios.csproj
  src/Games/NexusMods.Games.DarkestDungeon/NexusMods.Games.DarkestDungeon.csproj
  src/Games/NexusMods.Games.Generic/NexusMods.Games.Generic.csproj
  src/Games/NexusMods.Games.RedEngine/NexusMods.Games.RedEngine.csproj
  src/Games/NexusMods.Games.Reshade/NexusMods.Games.Reshade.csproj
  src/Games/NexusMods.Games.Reshade/ReshadePresetInstaller.cs
  src/Networking/NexusMods.Networking.HttpDownloader/NexusMods.Networking.HttpDownloader.csproj
  src/Networking/NexusMods.Networking.NexusWebApi/DTOs/DownloadLink.cs
  src/Networking/NexusMods.Networking.NexusWebApi/NexusMods.Networking.NexusWebApi.csproj
  src/Networking/NexusMods.Networking.NexusWebApi/Types/UserInfo.cs
  src/NexusMods.App/NexusMods.App.csproj
  src/NexusMods.App/Program.cs
  src/NexusMods.CLI/NexusMods.CLI.csproj
  src/NexusMods.Common/NexusMods.Common.csproj
  src/NexusMods.DataModel.RateLimiting/NexusMods.DataModel.RateLimiting.csproj
  src/NexusMods.DataModel/Abstractions/EntityDictionary.cs
  src/NexusMods.DataModel/Games/RunGameTool.cs
  src/NexusMods.DataModel/JsonConverters/AExpressionConverterGenerator.cs
  src/NexusMods.DataModel/JsonConverters/ConcreteConverterGenerator.cs
  src/NexusMods.DataModel/Loadouts/Loadout.cs
  src/NexusMods.DataModel/Loadouts/Markers/LoadoutMarker.cs
  src/NexusMods.DataModel/NexusMods.DataModel.csproj
  src/NexusMods.DataModel/Sorting/Sorter.cs
  src/NexusMods.Hashing.xxHash64/NexusMods.Hashing.xxHash64.csproj
  src/NexusMods.Paths/NexusMods.Paths.csproj
Labels: small

#179 Fix Linux path issues
  src/NexusMods.Paths/AbsolutePath.cs
  tests/NexusMods.Paths.Tests/New/AbsolutePathTests/ConstructorTests.cs
  tests/NexusMods.Paths.Tests/New/AbsolutePathTests/FromFullPathTests.cs
Labels: bug :bug:

#181 More AbsolutePath fixes for Linux
  src/NexusMods.Paths/AbsolutePath.cs
  src/NexusMods.Paths/AbsolutePath_IO.cs
  tests/NexusMods.Paths.Tests/New/AbsolutePathTests/GetFullPathWithSpanTests.cs
  tests/NexusMods.Paths.Tests/New/AbsolutePathTests/UtilityTests.cs
Labels: bug :bug:

#187 More path fixes
  src/NexusMods.Paths/AbsolutePath.cs
  src/NexusMods.Paths/FileSystemAbstraction/InMemoryFileSystem/InMemoryFileSystem.cs
  src/NexusMods.Paths/HighPerformance/CommunityToolkit/SpanHelper.cs
  tests/NexusMods.Paths.Tests/FileSystem/InMemoryFileSystemTests.cs
  tests/NexusMods.Paths.Tests/New/AbsolutePathTests/CombineCheckedTest.cs
  tests/NexusMods.Paths.Tests/New/AbsolutePathTests/ConstructorTests.cs
  tests/NexusMods.Paths.Tests/New/AbsolutePathTests/FromFullPathTests.cs
  tests/NexusMods.Paths.Tests/New/AbsolutePathTests/GetFullPathTest.cs
  tests/NexusMods.Paths.Tests/New/AbsolutePathTests/GetFullPathTests.cs
  tests/NexusMods.Paths.Tests/New/AbsolutePathTests/IOTests.cs
  tests/NexusMods.Paths.Tests/New/AbsolutePathTests/UtilityTests.cs
Labels: bug :bug:

#188 Added: Documentation, Misc Cleanups & TODOs for RateLimiting
  src/ArchiveManagement/NexusMods.FileExtractor/Extractors/SevenZipExtractor.cs
  src/Networking/NexusMods.Networking.HttpDownloader/AdvancedHttpDownloader.cs
  src/Networking/NexusMods.Networking.HttpDownloader/SimpleHttpDownloader.cs
  src/NexusMods.DataModel.RateLimiting/Extensions/CollectionExtensions.cs
  src/NexusMods.DataModel.RateLimiting/Extensions/ResourceExtensions.cs
  src/NexusMods.DataModel.RateLimiting/IJob.cs
  src/NexusMods.DataModel.RateLimiting/IResource.cs
  src/NexusMods.DataModel.RateLimiting/Job.cs
  src/NexusMods.DataModel.RateLimiting/Percent.cs
  src/NexusMods.DataModel.RateLimiting/Resource.cs
  src/NexusMods.DataModel.RateLimiting/ResourceExtensions.cs
  src/NexusMods.DataModel.RateLimiting/StatusReport.cs
  src/NexusMods.DataModel/FileAnalyzer.cs
  src/NexusMods.DataModel/FileHashCache.cs
  src/NexusMods.DataModel/Loadouts/Markers/LoadoutMarker.cs
  src/NexusMods.Hashing.xxHash64/StreamExtensions.cs
  tests/NexusMods.DataModel.RateLimiting.Tests/PercentTests.cs
  tests/NexusMods.DataModel.RateLimiting.Tests/RateLimiterTests.cs
Labels: documentation :paperclip:, small, improvement :chart_with_upwards_trend:

#190 DataModel Tests: Cleanup Warnings & Problems
  src/NexusMods.DataModel/Loadouts/Markers/LoadoutMarker.cs
  tests/NexusMods.DataModel.Tests/ApplicationTests.cs
  tests/NexusMods.DataModel.Tests/ArchiveContentsCacheTests.cs
  tests/NexusMods.DataModel.Tests/DataStoreTests.cs
  tests/NexusMods.DataModel.Tests/Harness/ADataModelTest.cs
  tests/NexusMods.DataModel.Tests/ModSortingTests.cs
  tests/NexusMods.DataModel.Tests/ModelTests.cs
  tests/NexusMods.DataModel.Tests/SerializerTests.cs
  tests/NexusMods.DataModel.Tests/SortTests.cs
  tests/NexusMods.DataModel.Tests/Startup.cs
  tests/NexusMods.DataModel.Tests/ToolTests.cs
Labels: small

#192 Added: Documentation, Misc Cleanups & TODOs for `NexusMods.Hashing.xxHash64`
  NexusMods.App.sln.DotSettings
  benchmarks/NexusMods.Benchmarks/Benchmarks/XxHash64.cs
  src/Games/NexusMods.Games.BethesdaGameStudios/PluginFile.cs
  src/Networking/NexusMods.Networking.HttpDownloader/AdvancedHttpDownloader.cs
  src/Networking/NexusMods.Networking.HttpDownloader/SimpleHttpDownloader.cs
  src/NexusMods.DataModel/ArchiveManager.cs
  src/NexusMods.DataModel/FileAnalyzer.cs
  src/NexusMods.DataModel/FileHashCache.cs
  src/NexusMods.DataModel/Loadouts/Markers/LoadoutMarker.cs
  src/NexusMods.DataModel/SqliteDataStore.cs
  src/NexusMods.Hashing.xxHash64/AbsolutePathExtensions.cs
  src/NexusMods.Hashing.xxHash64/ByteArrayExtensions.cs
  src/NexusMods.Hashing.xxHash64/Hash.cs
  src/NexusMods.Hashing.xxHash64/HashRelativePath.cs
  src/NexusMods.Hashing.xxHash64/SpanExtensions.cs
  src/NexusMods.Hashing.xxHash64/StreamExtensions.cs
  src/NexusMods.Hashing.xxHash64/StringExtensions.cs
  src/NexusMods.Hashing.xxHash64/XxHash64Algorithm.cs
  tests/Games/NexusMods.Games.BethesdaGameStudios.Tests/SkyrimSpecialEditionTests.cs
  tests/NexusMods.DataModel.Tests/ApplicationTests.cs
  tests/NexusMods.DataModel.Tests/Harness/ADataModelTest.cs
  tests/NexusMods.FileExtractor.Tests/GenericExtractionTests.cs
  tests/NexusMods.FileExtractor.Tests/SevenZipExtractionTests.cs
  tests/NexusMods.Hashing.xxHash64.Tests/HashTests.cs
  tests/NexusMods.Hashing.xxHash64.Tests/StreamExtensionTests.cs
  tests/NexusMods.Hashing.xxHash64.Tests/StringExtensionTest.cs
  tests/NexusMods.StandardGameLocators.TestHelpers/StubbedGames.cs
Labels: documentation :paperclip:, small, improvement :chart_with_upwards_trend:

#219 Added: Faster Image Blur without Re-Encode (fixes #194)
  src/NexusMods.App.UI/Controls/GameWidget/GameWidget.axaml.cs
  src/NexusMods.App.UI/Controls/GameWidget/IGameWidgetViewModel.cs
  src/NexusMods.App.UI/Extensions/SkiaAvaloniaExtensions.cs
  src/NexusMods.App.UI/Extensions/SkiaExtensions.cs
Labels: small

#216 Added: Links to relevant issues for each TODO with an issue
  src/Networking/NexusMods.Networking.NexusWebApi/DTOs/Category.cs
  src/Networking/NexusMods.Networking.NexusWebApi/DTOs/ModUpdate.cs
  src/NexusMods.CLI/Verbs/ExportLoadout.cs
  src/NexusMods.Common/IDGenerator.cs
  src/NexusMods.DataModel.RateLimiting/Extensions/CollectionExtensions.cs
  src/NexusMods.DataModel.RateLimiting/Extensions/ResourceExtensions.cs
  src/NexusMods.DataModel.RateLimiting/Job.cs
  src/NexusMods.DataModel.RateLimiting/Percent.cs
  src/NexusMods.DataModel.RateLimiting/Resource.cs
  src/NexusMods.DataModel/Abstractions/IDataStore.cs
  src/NexusMods.DataModel/Abstractions/Ids/Id64.cs
  src/NexusMods.DataModel/ArchiveManager.cs
  src/NexusMods.DataModel/FileHashCache.cs
  src/NexusMods.DataModel/Games/AGame.cs
  src/NexusMods.DataModel/Interprocess/InterprocessProducer.cs
  src/NexusMods.DataModel/Interprocess/Messages/IdUpdated.cs
  src/NexusMods.DataModel/Interprocess/SqliteIPC.cs
  src/NexusMods.DataModel/Loadouts/LoadoutManager.cs
  src/NexusMods.DataModel/SqliteDataStore.cs
  src/NexusMods.Hashing.xxHash64/AbsolutePathExtensions.cs
  src/NexusMods.Hashing.xxHash64/HashRelativePath.cs
  src/NexusMods.Hashing.xxHash64/StringExtensions.cs
  src/NexusMods.Paths/AbsolutePath.cs
  tests/Games/NexusMods.Games.RedEngine.Tests/ModInstallerTests.cs
  tests/NexusMods.DataModel.RateLimiting.Tests/PercentTests.cs
Labels: small

#222 Implement Configuration and Fix File Logging Issues (fixes #218 , fixes #126)
  src/ArchiveManagement/NexusMods.FileExtractor/IFileExtractorSettings.cs
  src/ArchiveManagement/NexusMods.FileExtractor/NexusMods.FileExtractor.csproj
  src/ArchiveManagement/NexusMods.FileExtractor/Services.cs
  src/ArchiveManagement/NexusMods.FileExtractor/TemporaryFileManagerEx.cs
  src/Networking/NexusMods.Networking.HttpDownloader/AdvancedHttpDownloader.cs
  src/Networking/NexusMods.Networking.HttpDownloader/IHttpDownloaderSettings.cs
  src/Networking/NexusMods.Networking.HttpDownloader/Services.cs
  src/NexusMods.App/AppConfig.cs
  src/NexusMods.App/AppConfig.json
  src/NexusMods.App/NexusMods.App.csproj
  src/NexusMods.App/Program.cs
  src/NexusMods.App/Services.cs
  src/NexusMods.DataModel/IDataModelSettings.cs
  src/NexusMods.DataModel/Services.cs
  src/NexusMods.Paths/ConfigurationPath.cs
  src/NexusMods.Paths/Utilities/KnownFolders.cs
  src/NexusMods.Paths/Utilities/ThrowHelpers.cs
  tests/Games/NexusMods.Games.BethesdaGameStudios.Tests/Startup.cs
  tests/Games/NexusMods.Games.RedEngine.Tests/Startup.cs
  tests/NexusMods.CLI.Tests/Startup.cs
  tests/NexusMods.DataModel.Tests/Startup.cs
  tests/NexusMods.FileExtractor.Tests/Startup.cs
  tests/NexusMods.Paths.Tests/PathExpansionTests.cs
Labels: small

#226 Convert "Maximize" button to a toggle
  src/NexusMods.App.UI/Controls/TopBar/ITopBarViewModel.cs
  src/NexusMods.App.UI/Controls/TopBar/TopBarDesignViewModel.cs
  src/NexusMods.App.UI/Controls/TopBar/TopBarView.axaml.cs
  src/NexusMods.App.UI/Controls/TopBar/TopBarViewModel.cs
  src/NexusMods.App.UI/Windows/MainWindow.axaml.cs
Labels: small
