Repository Nexus-Mods/NexusMods.App, pull requests merged in 2024-03, with the labels that each got.

#1026 Add diagnostic for missing SMAPI
  src/Games/NexusMods.Games.StardewValley/Diagnostics.cs
  src/Games/NexusMods.Games.StardewValley/Emitters/MissingSMAPIEmitter.cs
  src/Games/NexusMods.Games.StardewValley/Installers/SMAPIInstaller.cs
  src/Games/NexusMods.Games.StardewValley/Installers/SMAPIModInstaller.cs
  src/Games/NexusMods.Games.StardewValley/Models/SMAPIMarker.cs
  src/Games/NexusMods.Games.StardewValley/Models/SMAPIModMarker.cs
  src/Games/NexusMods.Games.StardewValley/Services.cs
  src/Games/NexusMods.Games.StardewValley/TypeFinder.cs
Labels: area-game-support

#1037 Reorder grid states
  src/NexusMods.App.UI/WorkspaceSystem/GridUtils.cs
  tests/NexusMods.UI.Tests/WorkspaceSystem/GridUtilsTests/GetPossibleStatesTests.cs
Labels: area-panel-system

#1046 Workspace documentation
  .gitignore
  NexusMods.App.sln
  NexusMods.App.sln.DotSettings
  docs/development-guidelines/UsingWorkspaces.md
  docs/requirements.txt
  mkdocs.yml
  src/Examples/Examples.csproj
  src/Examples/README.md
  src/Examples/Workspaces/001-querying-windows-and-workspaces.cs
  src/Examples/Workspaces/002-opening-new-pages.cs
  src/Examples/Workspaces/003-creating-new-pages.cs
  src/Examples/Workspaces/README.md
  src/NexusMods.App.UI/WorkspaceSystem/Page/APageViewModel.cs
Labels: area-documentation

#1052 Update `GetDefaultOpenPageBehavior`
  src/Examples/Workspaces/002-opening-new-pages.cs
  src/NexusMods.App.UI/LeftMenu/Downloads/DownloadsLeftMenuViewModel.cs
  src/NexusMods.App.UI/LeftMenu/Home/HomeLeftMenuViewModel.cs
  src/NexusMods.App.UI/LeftMenu/Loadout/LoadoutLeftMenuViewModel.cs
  src/NexusMods.App.UI/NexusMods.App.UI.csproj.DotSettings
  src/NexusMods.App.UI/WorkspaceSystem/Page/APageViewModel.cs
  src/NexusMods.App.UI/WorkspaceSystem/Page/IPageFactory.cs
  src/NexusMods.App.UI/WorkspaceSystem/Page/PageFactoryController.cs
  src/NexusMods.App.UI/WorkspaceSystem/PageIdBundle.cs
  src/NexusMods.App.UI/WorkspaceSystem/Workspace/WorkspaceViewModel.cs
  src/NexusMods.App.UI/WorkspaceSystem/WorkspaceController/AddPanelBehavior.cs
  src/NexusMods.App.UI/WorkspaceSystem/WorkspaceController/IWorkspaceController.cs
  src/NexusMods.App.UI/WorkspaceSystem/WorkspaceController/NavigationInput.cs
  src/NexusMods.App.UI/WorkspaceSystem/WorkspaceController/OpenPageBehavior.cs
  src/NexusMods.App.UI/WorkspaceSystem/WorkspaceController/OpenPageBehaviorSettings.cs
  src/NexusMods.App.UI/WorkspaceSystem/WorkspaceController/OpenPageBehaviorType.cs
  src/NexusMods.App.UI/WorkspaceSystem/WorkspaceController/WorkspaceController.cs
Labels: area-workspace-system

#1059 Remove `UpdaterViewModelTests`
  tests/NexusMods.UI.Tests/Overlays/UpdaterViewModelTests.cs
Labels: meta-bug

#1064 Downgrade the `Microsoft.CodeAnalaysis.CSharp*` packages
  .github/dependabot.yml
  Directory.Packages.props
Labels: meta-bug

#1090 Added: A Writer Lock for SqliteDataStore
  src/NexusMods.DataModel/FileHashCache.cs
  src/NexusMods.DataModel/SqliteDataStore.cs
Labels: meta-bug, area-data-store

#1085 Better `IDiagnosticWriter` API
  src/Abstractions/NexusMods.Abstractions.Games.Diagnostics/Diagnostic.cs
  src/Abstractions/NexusMods.Abstractions.Games.Diagnostics/IDiagnosticMessageData.cs
  src/Abstractions/NexusMods.Abstractions.Games.Diagnostics/IDiagnosticWriter.cs
  src/NexusMods.App.Generators.Diagnostics/NexusMods.App.Generators.Diagnostics/DiagnosticTemplateIncrementalSourceGenerator.cs
  src/NexusMods.App.UI/Controls/Diagnostics/DiagnosticEntryDesignViewModel.cs
  src/NexusMods.App.UI/Controls/Diagnostics/DiagnosticEntryViewModel.cs
  src/NexusMods.App.UI/DiagnosticSystem/DiagnosticWriter.cs
  src/NexusMods.App.UI/DiagnosticSystem/IValueFormatter.cs
  src/NexusMods.App.UI/DiagnosticSystem/LoadoutReferenceFormatter.cs
  src/NexusMods.App.UI/DiagnosticSystem/ModReferenceFormatter.cs
  src/NexusMods.App.UI/DiagnosticSystem/NamedLinkFormatter.cs
  src/NexusMods.App.UI/DiagnosticSystem/ValueFormatterCache.cs
  src/NexusMods.App.UI/NexusMods.App.UI.csproj
  src/NexusMods.App.UI/Pages/Diagnostics/Details/DiagnosticDetailsViewModel.cs
  src/NexusMods.App.UI/Services.cs
  tests/NexusMods.App.Generators.Diagnostics.Tests/DiagnosticTemplateIncrementalSourceGeneratorTests.TestGenerator#TestNamespace.MyClass.Diagnostic1Template.g.verified.cs
Labels: tech-debt

#1098 Add "Required dependency is disabled" diagnostic
  src/Games/NexusMods.Games.StardewValley/Diagnostics.cs
  src/Games/NexusMods.Games.StardewValley/Emitters/DependencyDiagnosticEmitter.cs
Labels: area-game-support, area-diagnostics

#1100 Run git builds on schedule
  .github/workflows/git-builds.yaml
Labels: area-CI

#1114 Show diagnostic count
  src/Abstractions/NexusMods.Abstractions.Games.Diagnostics/IDiagnosticManager.cs
  src/NexusMods.App.UI/LeftMenu/Loadout/LoadoutLeftMenuViewModel.cs
  src/NexusMods.DataModel/Diagnostics/DiagnosticManager.cs
Labels: area-diagnostics

#1120 Fix steam launch on Linux
  src/Abstractions/NexusMods.Abstractions.Games/RunGameTool.cs
Labels: os-linux

#1072 Added: Support for Enhanced Tree Node Icons
  Directory.Packages.props
  src/Abstractions/NexusMods.Abstractions.GameLocators/Trees/GamePathNode.cs
  src/Games/NexusMods.Games.AdvancedInstaller.UI/Content/Left/ModContent/TreeEntry/ModContentTreeEntryView.axaml.cs
  src/Games/NexusMods.Games.AdvancedInstaller.UI/Content/Right/Preview/TreeEntry/PreviewTreeEntryView.axaml.cs
  src/Games/NexusMods.Games.RedEngine/ModInstallers/AppearancePreset.cs
  src/NexusMods.App.UI/Controls/Trees/Common/FileTreeNodeIconType.cs
  src/NexusMods.App.UI/Controls/Trees/Files/FileTreeNodeDesignViewModel.cs
  src/NexusMods.App.UI/Controls/Trees/Files/FileTreeNodeView.axaml.cs
  src/NexusMods.App.UI/Controls/Trees/Files/FileTreeNodeViewModel.cs
  src/NexusMods.App.UI/Controls/Trees/Files/IFileTreeNodeViewModel.cs
  src/Themes/NexusMods.Themes.NexusFluentDark/Styles/Controls/Icons/IconsStyles.axaml
Labels: meta-improvement, status-blocked, area-ui, area-advanced-installer

#1130 Use `$OWD` instead of `EntryDirectory`
  src/NexusMods.App/AppConfig.cs
Labels: os-linux

#1136 Remove legacy benchmarks
  benchmarks/NexusMods.Benchmarks/Benchmarks/Paths.cs
  benchmarks/NexusMods.Benchmarks/Benchmarks/XxHash64.cs
Labels: meta-chore

#1143 Removed Database Transaction Bottlenecks
  src/Abstractions/NexusMods.Abstractions.Serialization/DataModel/EntityDictionary.cs
  src/Abstractions/NexusMods.Abstractions.Serialization/DataModel/EntityExtensions.cs
  src/Abstractions/NexusMods.Abstractions.Serialization/IDataStore.cs
  src/NexusMods.DataModel/FileHashCache.cs
  src/NexusMods.DataModel/NxFileStore.cs
  src/NexusMods.DataModel/SqliteDataStore.cs
  tests/NexusMods.DataModel.Tests/Harness/ADataModelTest.cs
Labels: meta-performance

#1142 Add diagnostic docs
  docs/development-guidelines/Diagnostics.md
  mkdocs.yml
  src/Abstractions/NexusMods.Abstractions.Games.Diagnostics/DiagnosticSeverity.cs
  src/Examples/Diagnostics/README.md
  src/Examples/Diagnostics/UsingDiagnostics.cs
  src/Examples/Examples.csproj
  src/Examples/README.md
Labels: area-documentation, area-diagnostics

#1133 Added: Documentation for TreeDataGrid Usage, Including Examples
  docs/development-guidelines/UICodingGuidelines.md
  docs/images/custom-column-treedatagrid.png
  docs/images/simple-treedatagrid.png
  docs/images/too-small-width-example.png
  src/Examples/Examples.csproj
  src/Examples/FodyWeavers.xml
  src/Examples/FodyWeavers.xsd
  src/Examples/Program.cs
  src/Examples/README.md
  src/Examples/TreeDataGrid/Basic/FileTreeDesignViewModel.cs
  src/Examples/TreeDataGrid/Basic/FileTreeView.axaml
  src/Examples/TreeDataGrid/Basic/FileTreeView.axaml.cs
  src/Examples/TreeDataGrid/Basic/IFileTreeViewModel.cs
  src/Examples/TreeDataGrid/Basic/ViewModel/FileDesignViewModel.cs
  src/Examples/TreeDataGrid/Basic/ViewModel/IFileViewModel.cs
  src/Examples/TreeDataGrid/README.md
  src/Examples/TreeDataGrid/SingleColumn/FileColumn/FileColumnDesignViewModel.cs
  src/Examples/TreeDataGrid/SingleColumn/FileColumn/FileColumnView.axaml
  src/Examples/TreeDataGrid/SingleColumn/FileColumn/FileColumnView.axaml.cs
  src/Examples/TreeDataGrid/SingleColumn/FileColumn/IFileColumnViewModel.cs
  src/Examples/TreeDataGrid/SingleColumn/FileTreeDesignViewModel.cs
  src/Examples/TreeDataGrid/SingleColumn/FileTreeView.axaml
  src/Examples/TreeDataGrid/SingleColumn/FileTreeView.axaml.cs
  src/Examples/TreeDataGrid/SingleColumn/IFileTreeViewModel.cs
  src/NexusMods.App.UI/Helpers/TreeDataGrid/IDynamicDataTreeItem.cs
Labels: area-documentation
