Repository Nexus-Mods/NexusMods.App, pull requests merged in 2024-09, with the labels that each got.

#1949 Added: Chevron to Diagnostic Items & Drop Shadow
  src/NexusMods.App.UI/Controls/Diagnostics/DiagnosticEntryView.axaml
  src/NexusMods.App.UI/Pages/Diagnostics/List/DiagnosticListView.axaml
  src/NexusMods.Icons/IconValues.cs
  src/Themes/NexusMods.Themes.NexusFluentDark/Styles/UserControls/Diagnostics/DiagnosticEntryStyles.axaml
Labels: Design UI/UX, Dev UI

#1960 change markdown hyperlink styles
  src/NexusMods.App.UI/Controls/MarkdownRenderer/MarkdownRendererView.axaml
  src/Themes/NexusMods.Themes.NexusFluentDark/Assets/Fonts/Regular/RobotoMono-Regular.ttf
  src/Themes/NexusMods.Themes.NexusFluentDark/NexusMods.Themes.NexusFluentDark.csproj
  src/Themes/NexusMods.Themes.NexusFluentDark/Resources/Palette/Fonts/PrimitiveFonts.axaml
  src/Themes/NexusMods.Themes.NexusFluentDark/Resources/Palette/Fonts/SemanticFonts.axaml
Labels: Design UI/UX, Dev UI

#1964 Runtime dependency checker
  NexusMods.App.sln.DotSettings
  src/NexusMods.CrossPlatform/NexusMods.CrossPlatform.csproj
  src/NexusMods.CrossPlatform/Process/AOSInterop.cs
  src/NexusMods.CrossPlatform/Process/ExecutableRuntimeDependency.cs
  src/NexusMods.CrossPlatform/Process/IRuntimeDependency.cs
  src/NexusMods.CrossPlatform/Process/OSInteropLinux.cs
  src/NexusMods.CrossPlatform/Process/OSInteropOSX.cs
  src/NexusMods.CrossPlatform/Process/OSInteropWindows.cs
  src/NexusMods.CrossPlatform/Process/ProcessFactory.cs
  src/NexusMods.CrossPlatform/Process/RuntimeDependencyChecker.cs
  src/NexusMods.CrossPlatform/Process/UpdateDesktopDatabaseDependency.cs
  src/NexusMods.CrossPlatform/Process/XDGOpenDependency.cs
  src/NexusMods.CrossPlatform/Process/XDGSettingsDependency.cs
  src/NexusMods.CrossPlatform/ProtocolRegistration/ProtocolRegistrationLinux.cs
  src/NexusMods.CrossPlatform/ProtocolRegistration/ProtocolRegistrationOSX.cs
  src/NexusMods.CrossPlatform/ProtocolRegistration/ProtocolRegistrationWindows.cs
  src/NexusMods.CrossPlatform/Services.cs
  tests/NexusMods.CrossPlatform.Tests/UpdateDesktopDatabaseDependencyTests.cs
  tests/NexusMods.CrossPlatform.Tests/XDGOpenDependencyTests.cs
  tests/NexusMods.CrossPlatform.Tests/XDGSettingsDependencyTests.cs
Labels: os-linux

#1968 Added: Documentation on Running Windows Tools via WINE
  docs/developers/decisions/backend/0018-running-tools-on-linux.md
  mkdocs.yml
Labels: os-linux

#1919 Fixed: Building NMA with System Extractor
  Directory.Build.props
  src/ArchiveManagement/NexusMods.FileExtractor/Extractors/SevenZipExtractor.cs
  src/ArchiveManagement/NexusMods.FileExtractor/build/NexusMods.FileExtractor.targets
Labels: Bug

#2013 Added: Scrolling for Library Delete Confirmation Dialog
  src/NexusMods.App.UI/Overlays/LibraryDeleteConfirmation/LibraryItemDeleteConfirmationView.axaml
Labels: Design UI/UX

#2015 Fixed: Adding Library Files no longer Adds Duplicates
  benchmarks/NexusMods.Benchmarks/Benchmarks/Loadouts/Harness/DummyFileStore.cs
  src/Abstractions/NexusMods.Abstractions.IO/IFileStore.cs
  src/Abstractions/NexusMods.Abstractions.Loadouts.Synchronizers/ALoadoutSynchronizer.cs
  src/NexusMods.App.UI/Pages/TextEdit/TextEditorPageViewModel.cs
  src/NexusMods.DataModel/NxFileStore.cs
  src/NexusMods.Library/AddLibraryFileJob.cs
  tests/NexusMods.Collections.Tests/CollectionInstallTests.CanInstallBasicCollection.verified.txt
Labels: Bug, area-filestore

#2053 Improved: Correctly Handle Duplicate files in GC
  docs/developers/decisions/backend/0017-garbage-collector-design.md
  src/NexusMods.App.GarbageCollection.DataModel/DataStoreReferenceMarker.cs
  src/NexusMods.App.GarbageCollection.DataModel/NxFileStoreUpdater.cs
  src/NexusMods.App.GarbageCollection.DataModel/RunGarbageCollector.cs
  tests/NexusMods.App.GarbageCollection.DataModel.Tests/NxFileStoreUpdaterTests.cs
Labels: Bug

#2054 Fixed: Edge Case Where Power Loss During GC within a (200-600 microsecond window) could break App
  src/NexusMods.App.GarbageCollection.DataModel/RunGarbageCollector.cs
  src/NexusMods.App.GarbageCollection.Nx/NxRepacker.cs
Labels: Bug, meta-improvement, Tech: data-store

#2055 Fixed: Adding Mods to Library no longer Adds Duplicate Files
  benchmarks/NexusMods.Benchmarks/Benchmarks/Loadouts/Harness/DummyFileStore.cs
  src/Abstractions/NexusMods.Abstractions.IO/IFileStore.cs
  src/Abstractions/NexusMods.Abstractions.Loadouts.Synchronizers/ALoadoutSynchronizer.cs
  src/NexusMods.App.UI/Pages/TextEdit/TextEditorPageViewModel.cs
  src/NexusMods.DataModel/NxFileStore.cs
  src/NexusMods.Library/AddLibraryFileJob.cs
  tests/NexusMods.Collections.Tests/CollectionInstallTests.CanInstallBasicCollection.verified.txt
Labels: Bug, area-filestore

#2063 Changed: Prevent possible FileStore Deadlocks on GC By Preventing Yielding to external code.
  src/NexusMods.App.GarbageCollection.DataModel/RunGarbageCollector.cs
  src/NexusMods.DataModel/NxFileStore.cs
Labels: Bug, area-filestore

#2049 Docs update
  docs/users/games/BaldursGate3.md
  docs/users/games/Cyberpunk2077.md
  docs/users/games/index.md
  docs/users/index.md
  mkdocs.yml
Labels: Documentation

#2045 Changelog for 0.6.1 release.
  CHANGELOG.md
  docs/changelog-assets/531dc13e8116620f8ded4a8a98b281da.webp
  docs/changelog-assets/823627a8ccb068dc1559d62cd3326ebe.webp
  docs/changelog-assets/8a591449d6a8cddc5d2bad7d1fd5c849.webp
Labels: Documentation
