Repository Nexus-Mods/NexusMods.App, pull requests merged in 2024-02, with the labels that each got.

#913 Update Stardew Valley docs
  docs/games/0002-StardewValley.md
Labels: area-documentation

#949 Add Support for Setting Execute Bit on Linux based on Extension (fixes #924)
  Directory.Packages.props
  src/Abstractions/NexusMods.Abstractions.Loadouts.Synchronizers/ALoadoutSynchronizer.cs
  tests/NexusMods.DataModel.Tests/ALoadoutSynchronizerTests.cs
Labels: meta-bug, os-linux, os-macOS

#954 Save and restore last window session
  src/NexusMods.App.UI/Controls/FoundGames/FoundGamesViewModel.cs
  src/NexusMods.App.UI/Controls/Spine/ISpineViewModel.cs
  src/NexusMods.App.UI/Controls/Spine/SpineDesignViewModel.cs
  src/NexusMods.App.UI/Controls/Spine/SpineViewModel.cs
  src/NexusMods.App.UI/Services.cs
  src/NexusMods.App.UI/TypeFinder.cs
  src/NexusMods.App.UI/Windows/DesignWindowManager.cs
  src/NexusMods.App.UI/Windows/IWindowManager.cs
  src/NexusMods.App.UI/Windows/MainWindow.axaml.cs
  src/NexusMods.App.UI/Windows/MainWindowViewModel.cs
  src/NexusMods.App.UI/Windows/WindowManager.cs
  src/NexusMods.App.UI/WorkspaceSystem/Context/DownloadsContext.cs
  src/NexusMods.App.UI/WorkspaceSystem/Context/EmptyContext.cs
  src/NexusMods.App.UI/WorkspaceSystem/Context/HomeContext.cs
  src/NexusMods.App.UI/WorkspaceSystem/Context/LoadoutContext.cs
  src/NexusMods.App.UI/WorkspaceSystem/Controllers/IWorkspaceController.cs
  src/NexusMods.App.UI/WorkspaceSystem/Controllers/WorkspaceController.cs
  src/NexusMods.App.UI/WorkspaceSystem/DataStore/WindowData.cs
  src/NexusMods.App.UI/WorkspaceSystem/DataStore/WorkspaceData.cs
  src/NexusMods.App.UI/WorkspaceSystem/NewTabPage/NewTabPageFactory.cs
  src/NexusMods.App.UI/WorkspaceSystem/Workspace/WorkspaceViewModel.cs
Labels: area-ui, area-panel-system

#976 Delete .github/workflows/code_quality.yml
  .github/workflows/code_quality.yml
Labels: tech-debt

#1013 Always override Stardew Valley launch file
  src/Games/NexusMods.Games.StardewValley/Installers/SMAPIInstaller.cs
  src/Games/NexusMods.Games.StardewValley/StardewValley.cs
Labels: area-game-support
