Repository Nexus-Mods/NexusMods.App, pull requests merged in 2024-06, with the labels that each got.

#1543 Added: Requested Mod Library Refinements
  src/NexusMods.App.Cli/ProtocolVerbs.cs
  src/NexusMods.App.UI/Assets/Icons/disk_20px.svg
  src/NexusMods.App.UI/Assets/nexus-logo-white.svg
  src/NexusMods.App.UI/Converters/BooleanInverterConverter.cs
  src/NexusMods.App.UI/Helpers/DataGridSelectedItemsAsObservableHelper.cs
  src/NexusMods.App.UI/Pages/LoadoutGrid/ILoadoutGridViewModel.cs
  src/NexusMods.App.UI/Pages/LoadoutGrid/LoadoutGridDesignViewModel.cs
  src/NexusMods.App.UI/Pages/LoadoutGrid/LoadoutGridView.axaml
  src/NexusMods.App.UI/Pages/LoadoutGrid/LoadoutGridView.axaml.cs
  src/NexusMods.App.UI/Pages/LoadoutGrid/LoadoutGridViewModel.cs
  src/NexusMods.App.UI/Pages/ModLibrary/FileOrigins/FileOriginEntry/FileOriginEntryViewModel.cs
  src/NexusMods.App.UI/Pages/ModLibrary/FileOrigins/FileOriginEntry/IFileOriginEntryViewModel.cs
  src/NexusMods.App.UI/Pages/ModLibrary/FileOrigins/FileOriginsPage.cs
  src/NexusMods.App.UI/Pages/ModLibrary/FileOrigins/FileOriginsPageView.axaml
  src/NexusMods.App.UI/Pages/ModLibrary/FileOrigins/FileOriginsPageView.axaml.cs
  src/NexusMods.App.UI/Pages/ModLibrary/FileOrigins/FileOriginsPageViewModel.cs
  src/NexusMods.App.UI/Pages/ModLibrary/FileOrigins/IFileOriginsPageViewModel.cs
  src/NexusMods.App.UI/Resources/Language.Designer.cs
  src/NexusMods.App.UI/Resources/Language.de.resx
  src/NexusMods.App.UI/Resources/Language.it.resx
  src/NexusMods.App.UI/Resources/Language.pl.resx
  src/NexusMods.App.UI/Resources/Language.resx
  src/NexusMods.Icons/IconValues.cs
  src/Themes/NexusMods.Themes.NexusFluentDark/Styles/Controls/Border/Toolbar.xaml
  src/Themes/NexusMods.Themes.NexusFluentDark/Styles/Controls/Icons/IconsStyles.axaml
  tests/NexusMods.CLI.Tests/VerbTests/AVerbTest.cs
Labels: Epic: Downloads

#1645 Additional Documentation
  docs/users/AddGames.md
  docs/users/GettingStarted.md
  docs/users/SystemRequirements.md
  docs/users/images/0.5.2/AddGameStardewValley.webp
  docs/users/images/0.5.2/AddingGameStardewValley.webp
  docs/users/images/0.5.2/GameAddedStardewValley.webp
  docs/users/images/0.5.2/Topbar.webp
  docs/users/images/OAuthSignIn.webp
  docs/users/images/OpenInAppBrowserPromptChrome.webp
  mkdocs.yml
Labels: Documentation

#1622 Fixed: As Many UI Issues as I can Handle
  src/Examples/TreeDataGrid/SingleColumn/FileColumn/FileColumnView.axaml
  src/Games/NexusMods.Games.AdvancedInstaller.UI/Content/Left/ModContent/TreeEntry/ModContentTreeEntryView.axaml
  src/Games/NexusMods.Games.AdvancedInstaller.UI/Content/Right/Preview/TreeEntry/PreviewTreeEntryView.axaml
  src/Games/NexusMods.Games.AdvancedInstaller.UI/Content/Right/SelectLocation/SuggestedEntry/SuggestedEntryView.axaml
  src/Games/NexusMods.Games.AdvancedInstaller.UI/Content/Right/SelectLocation/TreeEntry/SelectableTreeEntryView.axaml
  src/Games/NexusMods.Games.FOMOD.UI/Options/GuidedInstallerOptionView.axaml
  src/NexusMods.App.UI/Assets/Icons/collections.svg
  src/NexusMods.App.UI/Assets/Icons/discord.svg
  src/NexusMods.App.UI/Assets/Icons/forum.svg
  src/NexusMods.App.UI/Assets/Icons/list_filled_24px.svg
  src/NexusMods.App.UI/Assets/Icons/mod_library.svg
  src/NexusMods.App.UI/Assets/Icons/mods.svg
  src/NexusMods.App.UI/Assets/Icons/stethoscope_24px.svg
  src/NexusMods.App.UI/Controls/DataGrid/Helpers.cs
  src/NexusMods.App.UI/Controls/GameWidget/GameWidget.axaml
  src/NexusMods.App.UI/Controls/TopBar/TopBarView.axaml
  src/NexusMods.App.UI/Controls/Trees/DiffTreeViewModel.cs
  src/NexusMods.App.UI/Controls/Trees/FileTreeView.axaml
  src/NexusMods.App.UI/Controls/Trees/Files/FileTreeNodeView.axaml
  src/NexusMods.App.UI/Controls/Trees/ModFileTreeViewModel.cs
  src/NexusMods.App.UI/LeftMenu/Home/HomeLeftMenuViewModel.cs
  src/NexusMods.App.UI/LeftMenu/Items/IconView.axaml
  src/NexusMods.App.UI/LeftMenu/Loadout/LoadoutLeftMenuDesignViewModel.cs
  src/NexusMods.App.UI/Pages/Diagnostics/Details/DiagnosticDetailsViewModel.cs
  src/NexusMods.App.UI/Pages/LoadoutGrid/LoadoutGridView.axaml
  src/NexusMods.App.UI/Pages/ModLibrary/FileOrigins/FileOriginsPageView.axaml
  src/NexusMods.App.UI/Pages/MyGames/MyGamesViewModel.cs
  src/NexusMods.App.UI/Resources/Language.pl.resx
  src/NexusMods.App.UI/Resources/Language.resx
  src/NexusMods.App.UI/WorkspaceSystem/PanelTabHeader/PanelTabHeaderView.axaml
  src/NexusMods.DataModel/GameRegistry/Registry.cs
  src/NexusMods.Icons/IconValues.cs
  src/NexusMods.Icons/UnifiedIcon.cs
  src/Themes/NexusMods.Themes.NexusFluentDark/Styles/Controls/Border/Toolbar.xaml
  src/Themes/NexusMods.Themes.NexusFluentDark/Styles/Controls/Button/ButtonStyles.axaml
  src/Themes/NexusMods.Themes.NexusFluentDark/Styles/Controls/Button/RoundedButtonStyles.axaml
  src/Themes/NexusMods.Themes.NexusFluentDark/Styles/Controls/Button/SpineButtonStyles.axaml
  src/Themes/NexusMods.Themes.NexusFluentDark/Styles/Controls/Button/SpineDownloadButtonStyles.axaml
  src/Themes/NexusMods.Themes.NexusFluentDark/Styles/Controls/Icons/IconsStyles.axaml
  src/Themes/NexusMods.Themes.NexusFluentDark/Styles/UserControls/Banners/InfoBannerStyles.axaml
  src/Themes/NexusMods.Themes.NexusFluentDark/Styles/UserControls/WorkspaceSystem/PanelTabHeaderStyles.axaml
Labels: Design UI/UX

#1682 User docs
  docs/users/FAQ.md
  docs/users/images/FirefoxProtocols.webp
  mkdocs.yml
Labels: Documentation
