Repository Nexus-Mods/NexusMods.App, pull requests merged in 2024-01, with the labels that each got.

#826 Migrate to Trees 2.0
  Directory.Packages.props
  src/Games/NexusMods.Games.AdvancedInstaller.UI/AdvancedManualInstallerUI.cs
  src/Games/NexusMods.Games.AdvancedInstaller.UI/Content/BodyViewModel.cs
  src/Games/NexusMods.Games.AdvancedInstaller.UI/Content/Left/ModContent/ModContentViewModel.cs
  src/Games/NexusMods.Games.AdvancedInstaller.UI/DesignTimeHelpers.cs
  src/Games/NexusMods.Games.AdvancedInstaller.UI/Pages/AdvancedInstallerPages/AdvancedInstallerPageViewModel.cs
  src/Games/NexusMods.Games.AdvancedInstaller.UI/Window/AdvancedInstallerWindowViewModel.cs
  src/Games/NexusMods.Games.AdvancedInstaller/AdvancedManualInstaller.cs
  src/Games/NexusMods.Games.AdvancedInstaller/DeploymentData.cs
  src/Games/NexusMods.Games.AdvancedInstaller/DeploymentDataExtensions.cs
  src/Games/NexusMods.Games.BladeAndSorcery/Installers/BladeAndSorceryModInstaller.cs
  src/Games/NexusMods.Games.DarkestDungeon/Installers/LooseFilesModInstaller.cs
  src/Games/NexusMods.Games.DarkestDungeon/Installers/NativeModInstaller.cs
  src/Games/NexusMods.Games.FOMOD/CoreDelegates/UiDelegate.cs
  src/Games/NexusMods.Games.FOMOD/FomodAnalyzer.cs
  src/Games/NexusMods.Games.FOMOD/FomodXmlInstaller.cs
  src/Games/NexusMods.Games.Generic/Installers/GenericFolderMatchInstaller.cs
  src/Games/NexusMods.Games.MountAndBlade2Bannerlord/Installers/MountAndBlade2BannerlordModInstaller.cs
  src/Games/NexusMods.Games.RedEngine/ModInstallers/AppearancePreset.cs
  src/Games/NexusMods.Games.RedEngine/ModInstallers/FolderlessModInstaller.cs
  src/Games/NexusMods.Games.RedEngine/ModInstallers/Helpers.cs
  src/Games/NexusMods.Games.RedEngine/ModInstallers/RedModInstaller.cs
  src/Games/NexusMods.Games.RedEngine/ModInstallers/SimpleOverlayModInstaller.cs
  src/Games/NexusMods.Games.Reshade/ReshadePresetInstaller.cs
  src/Games/NexusMods.Games.Sifu/SifuModInstaller.cs
  src/Games/NexusMods.Games.StardewValley/Installers/SMAPIInstaller.cs
  src/Games/NexusMods.Games.StardewValley/Installers/SMAPIModInstaller.cs
  src/Games/NexusMods.Games.StardewValley/Models/SMAPIVersion.cs
  src/Games/NexusMods.Games.StardewValley/StardewValley.cs
  src/Networking/NexusMods.Networking.HttpDownloader/Services.cs
  src/NexusMods.Common/NexusMods.Common.csproj
  src/NexusMods.DataModel/Abstractions/DTOs/DownloadAnalysis.cs
  src/NexusMods.DataModel/Abstractions/Entity.cs
  src/NexusMods.DataModel/ArchiveInstaller.cs
  src/NexusMods.DataModel/Loadouts/DiskStateRegistry.cs
  src/NexusMods.DataModel/ModInstallers/AModInstaller.cs
  src/NexusMods.DataModel/ModInstallers/IModInstaller.cs
  src/NexusMods.DataModel/ModInstallers/ModSourceFileEntry.cs
  src/NexusMods.DataModel/NexusMods.DataModel.csproj
  src/NexusMods.DataModel/Trees/ModFileTree.cs
  src/NexusMods.DataModel/Trees/ModFileTreeSource.cs
  tests/Games/NexusMods.Games.AdvancedInstaller.Tests/DeploymentDataEmitTests.cs
  tests/Games/NexusMods.Games.AdvancedInstaller.Tests/DeploymentDataExtensionTests.cs
  tests/Games/NexusMods.Games.AdvancedInstaller.UI.Tests/AdvancedInstallerUITests.cs
  tests/Games/NexusMods.Games.AdvancedInstaller.UI.Tests/Helpers/AdvancedInstallerTestHelpers.cs
  tests/Games/NexusMods.Games.BladeAndSorcery.Tests/Installers/BladeAndSorceryModInstallerTests.cs
  tests/Games/NexusMods.Games.DarkestDungeon.Tests/Installers/LooseFilesModInstallerTests.cs
  tests/Games/NexusMods.Games.DarkestDungeon.Tests/Installers/NativeModInstallerTests.cs
  tests/Games/NexusMods.Games.FOMOD.Tests/FomodTestHelpers.cs
  tests/Games/NexusMods.Games.FOMOD.Tests/FomodXmlInstallerTests.cs
  tests/Games/NexusMods.Games.MountAndBlade2Bannerlord.Tests/Installers/MountAndBlade2BannerlordModInstallerTests.cs
  tests/Games/NexusMods.Games.Sifu.Tests/SifuModInstallerTests.cs
  tests/Games/NexusMods.Games.StardewValley.Tests/Installers/SMAPIInstallerTests.cs
  tests/Games/NexusMods.Games.StardewValley.Tests/Installers/SMAPIModInstallerTests.cs
  tests/Games/NexusMods.Games.TestFramework/AModInstallerTest.cs
  tests/NexusMods.CLI.Tests/VerbTests/DownloadAndInstallMod.cs
  tests/NexusMods.CLI.Tests/VerbTests/ListGames.cs
  tests/NexusMods.StandardGameLocators.TestHelpers/StubbedGames/StubbedGameInstaller.cs
Labels: meta-improvement

#856 Upgrade System.IdentityModel.Tokens.Jwt to 7.2.0
  .github/dependabot.yml
  Directory.Packages.props
Labels: area-dependencies

#872 Add Workspace and Tab controller
  src/NexusMods.App.UI/Controls/Dummy/DummyPage.cs
  src/NexusMods.App.UI/Controls/Dummy/DummyViewModel.cs
  src/NexusMods.App.UI/Extensions/OptionalExtensions.cs
  src/NexusMods.App.UI/NexusMods.App.UI.csproj
  src/NexusMods.App.UI/NexusMods.App.UI.csproj.DotSettings
  src/NexusMods.App.UI/RightContent/LoadoutGrid/LoadoutGridDesignViewModel.cs
  src/NexusMods.App.UI/RightContent/LoadoutGrid/LoadoutGridViewModel.cs
  src/NexusMods.App.UI/Services.cs
  src/NexusMods.App.UI/WorkspaceSystem/Controllers/AddPanelBehavior.cs
  src/NexusMods.App.UI/WorkspaceSystem/Controllers/DesignWorkspaceController.cs
  src/NexusMods.App.UI/WorkspaceSystem/Controllers/IWorkspaceController.cs
  src/NexusMods.App.UI/WorkspaceSystem/Controllers/OpenPageBehavior.cs
  src/NexusMods.App.UI/WorkspaceSystem/Controllers/WorkspaceController.cs
  src/NexusMods.App.UI/WorkspaceSystem/NewTabPage/NewTabPageDesignViewModel.cs
  src/NexusMods.App.UI/WorkspaceSystem/NewTabPage/NewTabPageFactory.cs
  src/NexusMods.App.UI/WorkspaceSystem/NewTabPage/NewTabPageViewModel.cs
  src/NexusMods.App.UI/WorkspaceSystem/Page/APageViewModel.cs
  src/NexusMods.App.UI/WorkspaceSystem/Page/IPageFactory.cs
  src/NexusMods.App.UI/WorkspaceSystem/Page/IPageViewModelInterface.cs
  src/NexusMods.App.UI/WorkspaceSystem/Page/Page.cs
  src/NexusMods.App.UI/WorkspaceSystem/Page/PageFactoryController.cs
  src/NexusMods.App.UI/WorkspaceSystem/Panel/IPanelViewModel.cs
  src/NexusMods.App.UI/WorkspaceSystem/Panel/PanelViewModel.cs
  src/NexusMods.App.UI/WorkspaceSystem/PanelTab/PanelTabViewModel.cs
  src/NexusMods.App.UI/WorkspaceSystem/Workspace/IWorkspaceViewModel.cs
  src/NexusMods.App.UI/WorkspaceSystem/Workspace/WorkspaceId.cs
  src/NexusMods.App.UI/WorkspaceSystem/Workspace/WorkspacePlaygroundViewModel.cs
  src/NexusMods.App.UI/WorkspaceSystem/Workspace/WorkspaceViewModel.cs
  src/NexusMods.DataModel/SqliteDataStore.cs
Labels: area-ui
