Repository Nexus-Mods/NexusMods.App, pull requests merged in 2024-12, with the labels that each got.

#2320 Added: Support for running Protontricks via Flatpak (and extra)
  src/Games/NexusMods.Games.Generic/GameToolRunner.cs
  src/Games/NexusMods.Games.MountAndBlade2Bannerlord/Diagnostics/MissingProtontricksEmitter.cs
  src/Games/NexusMods.Games.RedEngine/Cyberpunk2077/Emitters/MissingProtontricksForRedModEmitter.cs
  src/NexusMods.CrossPlatform/NexusMods.CrossPlatform.csproj
  src/NexusMods.CrossPlatform/Process/AggregateExecutableRuntimeDependency.cs
  src/NexusMods.CrossPlatform/Process/AggregateProtontricksDependency.cs
  src/NexusMods.CrossPlatform/Process/IProtontricksDependency.cs
  src/NexusMods.CrossPlatform/Process/ProtontricksFlatpakDependency.cs
  src/NexusMods.CrossPlatform/Process/ProtontricksNativeDependency.cs
  src/NexusMods.CrossPlatform/Services.cs
  tests/NexusMods.CrossPlatform.Tests/AggregateExecutableRuntimeDependencyTests.cs
  tests/NexusMods.CrossPlatform.Tests/ProtontricksTests.cs
Labels: Bug

#2321 Added: Support for BLSE (Bannerlord Software Extender)
  Directory.Packages.props
  src/Games/NexusMods.Games.MountAndBlade2Bannerlord/Bannerlord.cs
  src/Games/NexusMods.Games.MountAndBlade2Bannerlord/BannerlordRunGameTool.cs
  src/Games/NexusMods.Games.MountAndBlade2Bannerlord/Diagnostics/BannerlordDiagnosticEmitter.cs
  src/Games/NexusMods.Games.MountAndBlade2Bannerlord/Diagnostics/Diagnostics.cs
  src/Games/NexusMods.Games.MountAndBlade2Bannerlord/Installers/BLSEInstaller.cs
  src/Games/NexusMods.Games.MountAndBlade2Bannerlord/Installers/BannerlordModInstaller.cs
  src/Games/NexusMods.Games.MountAndBlade2Bannerlord/LoadoutExtensions.cs
  src/Games/NexusMods.Games.MountAndBlade2Bannerlord/Models/LoadoutModuleViewModel.cs
  src/Games/NexusMods.Games.MountAndBlade2Bannerlord/Services.cs
Labels: Epic: Game Support

#2361 German Locale update by Taija
  src/NexusMods.App.UI/Resources/Language.de.resx
Labels: meta-improvement, User Raised
