Repository Nexus-Mods/NexusMods.App, pull requests merged in 2024-10, with the labels that each got.

#2114 Improved: Uninstall Experience
  src/NexusMods.App/Commandline/CleanupVerbs.cs
Labels: Bug

#2119 Moved tooltip out of border
  src/NexusMods.App.UI/WorkspaceSystem/Panel/PanelView.axaml
Labels: Dev UI

#2121 Improved: Additional Set of Uninstaller Improvements
  src/NexusMods.App/Commandline/CleanupVerbs.cs
  src/NexusMods.DataModel/DataModelSettings.cs
Labels: Bug

#2092 [2/4] Added: Caching system for updates.
  NexusMods.App.sln
  src/Networking/NexusMods.Networking.ModUpdates/MultiFeedCacheUpdater.cs
  src/Networking/NexusMods.Networking.ModUpdates/NexusMods.Networking.ModUpdates.csproj
  src/Networking/NexusMods.Networking.ModUpdates/PerFeedCacheUpdater.cs
  src/Networking/NexusMods.Networking.ModUpdates/PerFeedCacheUpdaterResult.cs
  src/Networking/NexusMods.Networking.ModUpdates/Private/CacheUpdaterAction.cs
  src/Networking/NexusMods.Networking.ModUpdates/Structures/GameId.cs
  src/Networking/NexusMods.Networking.ModUpdates/Structures/ModId.cs
  src/Networking/NexusMods.Networking.ModUpdates/Structures/Uid.cs
  src/Networking/NexusMods.Networking.ModUpdates/Traits/ICanGetLastUpdatedTimestamp.cs
  src/Networking/NexusMods.Networking.ModUpdates/Traits/ICanGetUid.cs
  tests/Networking/NexusMods.Networking.ModUpdates.Tests/GlobalUsings.cs
  tests/Networking/NexusMods.Networking.ModUpdates.Tests/Helpers/TestItem.cs
  tests/Networking/NexusMods.Networking.ModUpdates.Tests/MultiFeedCacheUpdaterTests.cs
  tests/Networking/NexusMods.Networking.ModUpdates.Tests/NexusMods.Networking.ModUpdates.Tests.csproj
  tests/Networking/NexusMods.Networking.ModUpdates.Tests/PerFeedCacheUpdaterTests.cs
  tests/Networking/NexusMods.Networking.ModUpdates.Tests/Startup.cs
Labels: Epic: Updates

#2095 [3/4] Improve: Small Cleanup / Tech Debt Reduction Around NexusWebApi / V2 Types.
  src/Abstractions/NexusMods.Abstractions.Collections/Json/ModSource.cs
  src/Abstractions/NexusMods.Abstractions.NexusModsLibrary/NexusModsFileMetadata.cs
  src/Abstractions/NexusMods.Abstractions.NexusModsLibrary/NexusModsModPageMetadata.cs
  src/Abstractions/NexusMods.Abstractions.NexusWebApi/DTOs/GameInfo.cs
  src/Abstractions/NexusMods.Abstractions.NexusWebApi/DTOs/ModFile.cs
  src/Abstractions/NexusMods.Abstractions.NexusWebApi/DTOs/ModUpdate.cs
  src/Abstractions/NexusMods.Abstractions.NexusWebApi/INexusApiClient.cs
  src/Abstractions/NexusMods.Abstractions.NexusWebApi/NexusMods.Abstractions.NexusWebApi.csproj
  src/Abstractions/NexusMods.Abstractions.NexusWebApi/NexusModsArchiveMetadata.cs
  src/Abstractions/NexusMods.Abstractions.NexusWebApi/Types/FileId.cs
  src/Abstractions/NexusMods.Abstractions.NexusWebApi/Types/NXMModUrl.cs
  src/Abstractions/NexusMods.Abstractions.NexusWebApi/Types/V2/FileId.cs
  src/Abstractions/NexusMods.Abstractions.NexusWebApi/Types/V2/GameId.cs
  src/Abstractions/NexusMods.Abstractions.NexusWebApi/Types/V2/ModId.cs
  src/Abstractions/NexusMods.Abstractions.NexusWebApi/Types/V2/Uid/UidForFile.cs
  src/Abstractions/NexusMods.Abstractions.NexusWebApi/Types/V2/Uid/UidForMod.cs
  src/Games/NexusMods.Games.RedEngine/Cyberpunk2077/Emitters/Pattern.cs
  src/Games/NexusMods.Games.RedEngine/Cyberpunk2077/Emitters/PatternDefinitions.cs
  src/Games/NexusMods.Games.TestHarness/Verbs/StressTest.cs
  src/Networking/NexusMods.Networking.ModUpdates/MultiFeedCacheUpdater.cs
  src/Networking/NexusMods.Networking.ModUpdates/NexusMods.Networking.ModUpdates.csproj
  src/Networking/NexusMods.Networking.ModUpdates/PerFeedCacheUpdater.cs
  src/Networking/NexusMods.Networking.ModUpdates/PerFeedCacheUpdaterResult.cs
  src/Networking/NexusMods.Networking.ModUpdates/Traits/ICanGetUidForMod.cs
  src/Networking/NexusMods.Networking.NexusWebApi/Extensions/ClientExtensions.cs
  src/Networking/NexusMods.Networking.NexusWebApi/Extensions/FragmentExtensions.cs
  src/Networking/NexusMods.Networking.NexusWebApi/NexusApiClient.cs
  src/Networking/NexusMods.Networking.NexusWebApi/NexusApiVerbs.cs
  src/Networking/NexusMods.Networking.NexusWebApi/NexusModsLibrary.cs
  tests/Games/NexusMods.Games.TestFramework/Downloader/NexusModMetadata.cs
  tests/Networking/NexusMods.Networking.ModUpdates.Tests/Helpers/TestItem.cs
  tests/Networking/NexusMods.Networking.ModUpdates.Tests/MultiFeedCacheUpdaterTests.cs
  tests/Networking/NexusMods.Networking.ModUpdates.Tests/PerFeedCacheUpdaterTests.cs
  tests/Networking/NexusMods.Networking.NexusWebApi.Tests/Types/V2/UidForFileTests.cs
  tests/Networking/NexusMods.Networking.NexusWebApi.Tests/Types/V2/UidForModTests.cs
  tests/NexusMods.UI.Tests/ImageLoaderTests.cs
Labels: Epic: Tech-debt

#2118 Free Pill UI Banner
  src/NexusMods.App.UI/Controls/TopBar/ITopBarViewModel.cs
  src/NexusMods.App.UI/Controls/TopBar/TopBarDesignViewModel.cs
  src/NexusMods.App.UI/Controls/TopBar/TopBarView.axaml
  src/NexusMods.App.UI/Controls/TopBar/TopBarView.axaml.cs
  src/NexusMods.App.UI/Controls/TopBar/TopBarViewModel.cs
  src/NexusMods.App.UI/Resources/Language.Designer.cs
  src/NexusMods.App.UI/Resources/Language.resx
Labels: Dev UI

#2162 Improved: Empty State View
  src/NexusMods.App.UI/Pages/LibraryPage/LibraryView.axaml.cs
  src/Themes/NexusMods.Themes.NexusFluentDark/Styles/UserControls/EmptyState/EmptyStateStyles.axaml
Labels: Dev UI

#2148 New StandardButton component
  src/NexusMods.App.UI/Controls/StandardButton.axaml
  src/NexusMods.App.UI/Controls/StandardButton.axaml.cs
  src/NexusMods.Icons/IconValues.cs
  src/Themes/NexusMods.Themes.NexusFluentDark/Extensions/ThicknessExtension.cs
  src/Themes/NexusMods.Themes.NexusFluentDark/Resources/ControlThemes/StandardButtonControlTheme.axaml
  src/Themes/NexusMods.Themes.NexusFluentDark/Resources/Palette/Spacings/ElementSpacing.axaml
  src/Themes/NexusMods.Themes.NexusFluentDark/Resources/ResourceIndex.axaml
Labels: Design UI/UX

#2136 Update docs for the next release
  CHANGELOG.md
  docs/changelog-assets/8ed9a020e1532940c4d57a2753eae55a.webp
  docs/users/Uninstall.md
  docs/users/games/BaldursGate3.md
  docs/users/games/Cyberpunk2077.md
  docs/users/games/StardewValley.md
  docs/users/games/index.md
  docs/users/images/0.6.1/REDmodHeroicEnableMods.webp
  docs/users/images/0.6.1/REDmodHeroicModifyInstall.webp
  mkdocs.yml
Labels: Documentation

#2186 Alert component
  src/NexusMods.App.UI/Controls/Alerts/Alert.axaml
  src/NexusMods.App.UI/Controls/Alerts/Alert.axaml.cs
  src/NexusMods.App.UI/Controls/Alerts/AlertSettingsWrapper.cs
  src/NexusMods.App.UI/Controls/Banners/InfoBanner.cs
  src/NexusMods.App.UI/Controls/DevelopmentBuildBanner/DevelopmentBuildBannerView.axaml
  src/NexusMods.App.UI/NexusMods.App.UI.csproj
  src/NexusMods.App.UI/Settings/AlertSettings.cs
  src/NexusMods.App.UI/Settings/ServiceExtensions.cs
  src/NexusMods.App.UI/WorkspaceSystem/NewTabPage/INewTabPageViewModel.cs
  src/NexusMods.App.UI/WorkspaceSystem/NewTabPage/NewTabPageView.axaml
  src/NexusMods.App.UI/WorkspaceSystem/NewTabPage/NewTabPageView.axaml.cs
  src/NexusMods.App.UI/WorkspaceSystem/NewTabPage/NewTabPageViewModel.cs
  src/NexusMods.Icons/IconValues.cs
  src/Themes/NexusMods.Themes.NexusFluentDark/NexusMods.Themes.NexusFluentDark.csproj
  src/Themes/NexusMods.Themes.NexusFluentDark/Resources/ControlThemes/AlertControlTheme.axaml
  src/Themes/NexusMods.Themes.NexusFluentDark/Resources/ControlThemes/InfoBannerControlTheme.axaml
  src/Themes/NexusMods.Themes.NexusFluentDark/Resources/ResourceIndex.axaml
  src/Themes/NexusMods.Themes.NexusFluentDark/Styles/Controls/Button/StandardButtonStyles.axaml
  src/Themes/NexusMods.Themes.NexusFluentDark/Styles/Controls/Icons/IconsStyles.axaml
  src/Themes/NexusMods.Themes.NexusFluentDark/Styles/StylesIndex.axaml
  src/Themes/NexusMods.Themes.NexusFluentDark/Styles/UserControls/Banners/InfoBannerStyles.axaml
Labels: Design UI/UX

#2209 Improved: Edge Cases around the Apply & Launch Button
  src/Abstractions/NexusMods.Abstractions.Games/IGame.cs
  src/Abstractions/NexusMods.Abstractions.Games/RunGameTool.cs
  src/Abstractions/NexusMods.Abstractions.Jobs/IJobMonitorExtensions.cs
  src/Abstractions/NexusMods.Abstractions.Jobs/JobStatus.cs
  src/Abstractions/NexusMods.Abstractions.Loadouts/Exceptions/ExecutableInUseException.cs
  src/Abstractions/NexusMods.Abstractions.Loadouts/ISynchronizerService.cs
  src/Abstractions/NexusMods.Abstractions.Loadouts/ITool.cs
  src/Abstractions/NexusMods.Abstractions.Loadouts/IToolManager.cs
  src/Abstractions/NexusMods.Abstractions.Loadouts/NexusMods.Abstractions.Loadouts.csproj
  src/Games/NexusMods.Games.RedEngine/Cyberpunk2077/Cyberpunk2077Synchronizer.cs
  src/Games/NexusMods.Games.RedEngine/RedModDeployTool.cs
  src/NexusMods.App.UI/GameRunningTracker.cs
  src/NexusMods.App.UI/LeftMenu/Items/ApplyControlViewModel.cs
  src/NexusMods.App.UI/LeftMenu/Items/ILaunchButtonViewModel.cs
  src/NexusMods.App.UI/LeftMenu/Items/LaunchButtonDesignViewModel.cs
  src/NexusMods.App.UI/LeftMenu/Items/LaunchButtonView.axaml.cs
  src/NexusMods.App.UI/LeftMenu/Items/LaunchButtonViewModel.cs
  src/NexusMods.App.UI/LeftMenu/Loadout/LoadoutLeftMenuViewModel.cs
  src/NexusMods.App.UI/Overlays/Generic/MessageBox/Ok/IMessageBoxOkViewModel.cs
  src/NexusMods.App.UI/Overlays/Generic/MessageBox/Ok/MessageBoxOkView.axaml.cs
  src/NexusMods.App.UI/Overlays/Generic/MessageBox/Ok/MessageBoxOkViewModel.cs
  src/NexusMods.App.UI/Resources/Language.Designer.cs
  src/NexusMods.App.UI/Resources/Language.resx
  src/NexusMods.App.UI/Services.cs
  src/NexusMods.DataModel/Synchronizer/SynchronizerService.cs
  src/NexusMods.DataModel/ToolManager.cs
  tests/NexusMods.StandardGameLocators.TestHelpers/ListFilesTool.cs
Labels: Dev UI
