Repository Nexus-Mods/NexusMods.App, pull requests merged in 2025-02, with the labels that each got.

#2600 Collection instruction styling
  src/NexusMods.App.UI/Pages/CollectionDownload/CollectionDownloadDesignViewModel.cs
  src/NexusMods.App.UI/Pages/CollectionDownload/CollectionDownloadView.axaml
  src/Themes/NexusMods.Themes.NexusFluentDark/Styles/Controls/TabControl/TabControlStyles.axaml
  src/Themes/NexusMods.Themes.NexusFluentDark/Styles/UserControls/CollectionDownloadPage/CollectionDownloadPageStyles.axaml
Labels: Dev UI

#2613 Rework and style of TopBar
  src/Abstractions/NexusMods.Abstractions.NexusWebApi/ILoginManager.cs
  src/Abstractions/NexusMods.Abstractions.NexusWebApi/Types/UserInfo.cs
  src/Abstractions/NexusMods.Abstractions.NexusWebApi/Types/UserRole.cs
  src/Networking/NexusMods.Networking.NexusWebApi/Auth/ApiKeyMessageFactory.cs
  src/Networking/NexusMods.Networking.NexusWebApi/Auth/OAuth2MessageFactory.cs
  src/Networking/NexusMods.Networking.NexusWebApi/NexusApiVerbs.cs
  src/NexusMods.App.UI/Controls/StandardButton.cs
  src/NexusMods.App.UI/Controls/TopBar/ITopBarViewModel.cs
  src/NexusMods.App.UI/Controls/TopBar/TopBarDesignViewModel.cs
  src/NexusMods.App.UI/Controls/TopBar/TopBarView.axaml
  src/NexusMods.App.UI/Controls/TopBar/TopBarView.axaml.cs
  src/NexusMods.App.UI/Controls/TopBar/TopBarViewModel.cs
  src/NexusMods.App.UI/LeftMenu/Items/LeftMenuItemDesignViewModel.cs
  src/NexusMods.App.UI/Pages/Settings/SettingsPageViewModel.cs
  src/NexusMods.App.UI/Resources/Language.Designer.cs
  src/NexusMods.App.UI/Resources/Language.resx
  src/NexusMods.App.UI/WorkspaceSystem/AddPanelButton/AddPanelButtonView.axaml
  src/NexusMods.App.UI/WorkspaceSystem/AddPanelButton/AddPanelDropDownDesignViewModel.cs
  src/NexusMods.App.UI/WorkspaceSystem/AddPanelButton/AddPanelDropDownView.axaml
  src/NexusMods.App.UI/WorkspaceSystem/AddPanelButton/AddPanelDropDownView.axaml.cs
  src/NexusMods.App.UI/WorkspaceSystem/IconUtils.cs
  src/NexusMods.Icons/IconValues.cs
  src/Themes/NexusMods.Themes.NexusFluentDark/Resources/Palette/Opacities/ElementOpacities.axaml
  src/Themes/NexusMods.Themes.NexusFluentDark/Styles/Controls/Button/BareIconStyles.axaml
  src/Themes/NexusMods.Themes.NexusFluentDark/Styles/Controls/Button/StandardButtonStyles.axaml
  src/Themes/NexusMods.Themes.NexusFluentDark/Styles/Controls/ComboBox/ComboBoxStyles.addPanelDropDown.axaml
  src/Themes/NexusMods.Themes.NexusFluentDark/Styles/Controls/Icons/IconsStyles.axaml
  src/Themes/NexusMods.Themes.NexusFluentDark/Styles/UserControls/TopBar/TopBarStyles.axaml
  src/Themes/NexusMods.Themes.NexusFluentDark/Styles/UserControls/WorkspaceSystem/AddPanelButtonStyles.axaml
  tests/NexusMods.Telemetry.Tests/EventSenderTests.cs
Labels: Dev UI

#2625 Menu restyling
  src/NexusMods.App.UI/Pages/CollectionDownload/CollectionDownloadView.axaml
  src/Themes/NexusMods.Themes.NexusFluentDark/Styles/Controls/Menu/MenuItemStyles.axaml
Labels: Dev UI

#2622 TreeDataGrid styles update
  src/NexusMods.App.UI/Pages/CollectionDownload/CollectionComponents.cs
  src/NexusMods.App.UI/Pages/CollectionDownload/CollectionDownloadView.axaml
  src/NexusMods.App.UI/Pages/CollectionDownload/TreeDataGridCollectionResources.axaml
  src/NexusMods.App.UI/Pages/LibraryPage/LibraryComponents.cs
  src/NexusMods.App.UI/Pages/LibraryPage/LibraryView.axaml
  src/NexusMods.App.UI/Pages/LibraryPage/LibraryView.axaml.cs
  src/NexusMods.App.UI/Pages/LibraryPage/TreeDataGridLibraryResources.axaml
  src/NexusMods.App.UI/Pages/LoadoutPage/LoadoutComponents.cs
  src/NexusMods.App.UI/Pages/LoadoutPage/LoadoutView.axaml
  src/NexusMods.App.UI/Pages/LoadoutPage/LoadoutView.axaml.cs
  src/NexusMods.App.UI/Pages/TreeDataGridSharedResources.axaml
  src/NexusMods.App.UI/Resources/Language.Designer.cs
  src/NexusMods.App.UI/Resources/Language.resx
  src/Themes/NexusMods.Themes.NexusFluentDark/Styles/Controls/TreeDataGrid/SharedStyles.axaml
  src/Themes/NexusMods.Themes.NexusFluentDark/Styles/Controls/TreeDataGrid/TreeDataGridBaseStyles.axaml
  src/Themes/NexusMods.Themes.NexusFluentDark/Styles/Controls/TreeDataGrid/TreeDataGridCollectionDownloadStyles.axaml
  src/Themes/NexusMods.Themes.NexusFluentDark/Styles/Controls/TreeDataGrid/TreeDataGridLibraryStyles.axaml
  src/Themes/NexusMods.Themes.NexusFluentDark/Styles/Controls/TreeDataGrid/TreeDataGridOtherStyles.axaml
  src/Themes/NexusMods.Themes.NexusFluentDark/Styles/Controls/TreeDataGrid/TreeDataGridSortOrderStyles.axaml
  src/Themes/NexusMods.Themes.NexusFluentDark/Styles/StylesIndex.axaml
Labels: Dev UI

#2641 Fixes Mod files no longer having darker row colors
  src/Themes/NexusMods.Themes.NexusFluentDark/Styles/Controls/TreeDataGrid/TreeDataGridBaseStyles.axaml
Labels: Dev UI

#2634 Sdv preview docs
  docs/users/features/Loadouts.md
  docs/users/gettingstarted/AddGames.md
  docs/users/gettingstarted/DownloadACollection.md
  docs/users/gettingstarted/DownloadAMod.md
  docs/users/gettingstarted/Introduction.md
  docs/users/gettingstarted/MovingToTheApp.md
  docs/users/gettingstarted/index.md
  docs/users/images/0.6.0/Topbar.webp
  docs/users/images/0.7.3/AddFromDrive.webp
  docs/users/images/0.7.3/CollectionDownloadPage.webp
  docs/users/images/0.7.3/CollectionInLibrary.webp
  docs/users/images/0.7.3/CollectionLeftMenu.webp
  docs/users/images/0.7.3/CollectionReadyToInstall.webp
  docs/users/images/0.7.3/Topbar.webp
  docs/users/images/MO2DownloadFolder.webp
  docs/users/images/NexusModsCollectionPageDownload.webp
  docs/users/images/NexusModsModDownloadButtons.webp
  docs/users/images/StardropSettings.webp
  docs/users/images/VortexCreateCollection.webp
  mkdocs.yml
Labels: Documentation

#2649 Fixes for `DirectDownloadLibraryFile`
  src/Abstractions/NexusMods.Abstractions.Collections/DirectDownloadLibraryFile.cs
  src/Networking/NexusMods.Networking.NexusWebApi/ExternalDownloadJob.cs
  src/NexusMods.Collections/CollectionDownloader.cs
  src/NexusMods.DataModel.SchemaVersions/Migrations/_0006_DirectDownload.cs
  src/NexusMods.DataModel.SchemaVersions/Services.cs
  tests/NexusMods.DataModel.SchemaVersions.Tests/LegacyDatabaseSupportTests.TestDatabase_name=Issue-2608.rocksdb.zip.verified.txt
  tests/NexusMods.DataModel.SchemaVersions.Tests/LegacyDatabaseSupportTests.TestDatabase_name=Migration-5.rocksdb.zip.verified.txt
  tests/NexusMods.DataModel.SchemaVersions.Tests/LegacyDatabaseSupportTests.TestDatabase_name=Migration-6.rocksdb.zip.verified.txt
  tests/NexusMods.DataModel.SchemaVersions.Tests/LegacyDatabaseSupportTests.TestDatabase_name=SDV.2_5_2025.rocksdb.zip.verified.txt
  tests/NexusMods.DataModel.SchemaVersions.Tests/LegacyDatabaseSupportTests.TestDatabase_name=SDV.4_11_2024.rocksdb.zip.verified.txt
  tests/NexusMods.DataModel.SchemaVersions.Tests/MigrationSpecificTests/TestsFor_0006_DirectDownload.cs
  tests/NexusMods.DataModel.SchemaVersions.Tests/Resources/Databases/Descriptions.md
  tests/NexusMods.DataModel.SchemaVersions.Tests/Resources/Databases/Migration-6.rocksdb.zip
Labels: has-migration

#2648 Tweaks for development banner
  src/NexusMods.App.UI/Controls/DevelopmentBuildBanner/DevelopmentBuildBannerView.axaml
  src/NexusMods.App.UI/Controls/DevelopmentBuildBanner/DevelopmentBuildBannerView.axaml.cs
Labels: Dev UI

#2660 Various UI tweaks
  src/NexusMods.App.UI/Controls/GameWidget/GameWidget.axaml
  src/NexusMods.App.UI/Pages/Diagnostics/Details/DiagnosticDetailsView.axaml
  src/NexusMods.App.UI/Pages/TreeDataGridSharedResources.axaml
  src/NexusMods.App.UI/Resources/Language.Designer.cs
  src/NexusMods.App.UI/Resources/Language.resx
  src/NexusMods.App.UI/WorkspaceSystem/PanelTabHeader/PanelTabHeaderView.axaml
  src/Themes/NexusMods.Themes.NexusFluentDark/Styles/Controls/Border/Toolbar.xaml
  src/Themes/NexusMods.Themes.NexusFluentDark/Styles/Controls/Button/LeftMenuNavButtonStyles.axaml
  src/Themes/NexusMods.Themes.NexusFluentDark/Styles/Controls/Separator/SeparatorStyles.axaml
  src/Themes/NexusMods.Themes.NexusFluentDark/Styles/Controls/TreeDataGrid/SharedStyles.axaml
  src/Themes/NexusMods.Themes.NexusFluentDark/Styles/StylesIndex.axaml
  src/Themes/NexusMods.Themes.NexusFluentDark/Styles/UserControls/LeftMenu/LeftMenuStyles.axaml
Labels: Dev UI

#2642 Added: Remainder of Phase One of Updates.
  src/Abstractions/NexusMods.Abstractions.UI/ReactiveR3Object.cs
  src/Networking/NexusMods.Networking.ModUpdates/PerFeedCacheUpdaterResult.cs
  src/Networking/NexusMods.Networking.NexusWebApi/IModUpdateService.cs
  src/Networking/NexusMods.Networking.NexusWebApi/ModUpdateService.cs
  src/NexusMods.App.UI/Pages/LibraryPage/LibraryComponents.cs
  src/NexusMods.App.UI/Pages/LibraryPage/LibraryPage.cs
  src/NexusMods.App.UI/Pages/LibraryPage/LibraryViewModel.cs
  src/NexusMods.App.UI/Pages/NexusModsDataProvider.cs
Labels: Dev UI, Epic: Updates

#2680 Layout change for Collection Loadout Page
  src/NexusMods.App.UI/LeftMenu/Loadout/LoadoutLeftMenuViewModel.cs
  src/NexusMods.App.UI/Pages/CollectionDataProvider.cs
  src/NexusMods.App.UI/Pages/CollectionDownload/CollectionDownloadViewModel.cs
  src/NexusMods.App.UI/Pages/LoadoutPage/CollectionLoadoutDesignViewModel.cs
  src/NexusMods.App.UI/Pages/LoadoutPage/CollectionLoadoutView.axaml
  src/NexusMods.App.UI/Pages/LoadoutPage/CollectionLoadoutView.axaml.cs
  src/NexusMods.App.UI/Pages/LoadoutPage/CollectionLoadoutViewModel.cs
  src/NexusMods.App.UI/Pages/LoadoutPage/ICollectionLoadoutViewModel.cs
  src/NexusMods.Collections/InstallCollectionDownloadJob.cs
  src/NexusMods.Collections/Services.cs
  src/NexusMods.Collections/Verbs.cs
  src/NexusMods.Icons/IconValues.cs
  src/Themes/NexusMods.Themes.NexusFluentDark/Styles/Controls/Icons/IconsStyles.axaml
Labels: Dev UI

#2677 Various UI tweaks 2
  src/NexusMods.App.UI/Assets/Pictograms/celebrate.svg
  src/NexusMods.App.UI/ConstantLinks.cs
  src/NexusMods.App.UI/Controls/DevelopmentBuildBanner/DevelopmentBuildBannerDesignViewModel.cs
  src/NexusMods.App.UI/Controls/DevelopmentBuildBanner/DevelopmentBuildBannerView.axaml
  src/NexusMods.App.UI/Controls/DevelopmentBuildBanner/DevelopmentBuildBannerView.axaml.cs
  src/NexusMods.App.UI/Controls/DevelopmentBuildBanner/DevelopmentBuildBannerViewModel.cs
  src/NexusMods.App.UI/Controls/DevelopmentBuildBanner/IDevelopmentBuildBannerViewModel.cs
  src/NexusMods.App.UI/Controls/TopBar/ITopBarViewModel.cs
  src/NexusMods.App.UI/Controls/TopBar/TopBarDesignViewModel.cs
  src/NexusMods.App.UI/Controls/TopBar/TopBarView.axaml
  src/NexusMods.App.UI/Controls/TopBar/TopBarView.axaml.cs
  src/NexusMods.App.UI/Controls/TopBar/TopBarViewModel.cs
  src/NexusMods.App.UI/Overlays/AlphaWarning/AlphaWarningView.axaml
  src/NexusMods.App.UI/Overlays/AlphaWarning/AlphaWarningView.axaml.cs
  src/NexusMods.App.UI/Overlays/AlphaWarning/AlphaWarningViewModel.cs
  src/NexusMods.App.UI/Overlays/AlphaWarning/IAlphaWarningViewModel.cs
  src/NexusMods.App.UI/Resources/Language.Designer.cs
  src/NexusMods.App.UI/Resources/Language.resx
  src/NexusMods.Icons/IconValues.cs
  src/Themes/NexusMods.Themes.NexusFluentDark/Resources/Palette/Colors/BrandColors.axaml
  src/Themes/NexusMods.Themes.NexusFluentDark/Resources/Palette/Colors/ElementColors.axaml
  src/Themes/NexusMods.Themes.NexusFluentDark/Resources/Palette/Colors/PrimitiveColors.axaml
  src/Themes/NexusMods.Themes.NexusFluentDark/Styles/Controls/Icons/IconsStyles.axaml
  src/Themes/NexusMods.Themes.NexusFluentDark/Styles/Controls/Menu/MenuItemStyles.axaml
  src/Themes/NexusMods.Themes.NexusFluentDark/Styles/Controls/TreeDataGrid/TreeDataGridCollectionDownloadStyles.axaml
  src/Themes/NexusMods.Themes.NexusFluentDark/Styles/UserControls/CollectionDownloadPage/CollectionDownloadPageStyles.axaml
  src/Themes/NexusMods.Themes.NexusFluentDark/Styles/UserControls/TopBar/TopBarStyles.axaml
Labels: Dev UI

#2690 SDV diagnostic messages
  src/Games/NexusMods.Games.StardewValley/Diagnostics.cs
  src/Games/NexusMods.Games.StardewValley/Emitters/SMAPIGameVersionDiagnosticEmitter.cs
  src/Games/NexusMods.Games.StardewValley/Emitters/SMAPIModDatabaseCompatibilityDiagnosticEmitter.cs
  src/Games/NexusMods.Games.StardewValley/Resources/DiagnosticsTests/DisabledRequiredDependency.txt
  src/Games/NexusMods.Games.StardewValley/Resources/DiagnosticsTests/GameVersionNewerThanMaximumGameVersion.txt
  src/Games/NexusMods.Games.StardewValley/Resources/DiagnosticsTests/GameVersionOlderThanMinimumGameVersion.txt
  src/Games/NexusMods.Games.StardewValley/Resources/DiagnosticsTests/GameVersionOlderThanModMinimumGameVersion.txt
  src/Games/NexusMods.Games.StardewValley/Resources/DiagnosticsTests/MissingRequiredDependency.txt
  src/Games/NexusMods.Games.StardewValley/Resources/DiagnosticsTests/ModCompatabilityAssumeBroken.txt
  src/Games/NexusMods.Games.StardewValley/Resources/DiagnosticsTests/ModCompatabilityObsolete.txt
  src/Games/NexusMods.Games.StardewValley/Resources/DiagnosticsTests/ModOverwritesGameFiles.txt
  src/Games/NexusMods.Games.StardewValley/Resources/DiagnosticsTests/RequiredDependencyIsOutdated.txt
  src/Games/NexusMods.Games.StardewValley/Resources/DiagnosticsTests/SMAPIRequiredButDisabled.txt
  src/Games/NexusMods.Games.StardewValley/Resources/DiagnosticsTests/SMAPIRequiredButNotInstalled.txt
  src/Games/NexusMods.Games.StardewValley/Resources/DiagnosticsTests/SMAPIVersionOlderThanMinimumAPIVersion.txt
  src/Games/NexusMods.Games.StardewValley/Resources/DiagnosticsTests/SuggestSMAPIVersion.txt
  src/NexusMods.App.UI/DiagnosticSystem/LoadoutItemGroupFormatter.cs
Labels: Epic: Diagnostics

#2708 Various UI tweaks 3
  src/NexusMods.App.UI/Assets/collection-background-fallback.png
  src/NexusMods.App.UI/Controls/DevelopmentBuildBanner/DevelopmentBuildBannerView.axaml
  src/NexusMods.App.UI/Controls/StandardButton.cs
  src/NexusMods.App.UI/ImagePipelines.cs
  src/NexusMods.App.UI/Pages/CollectionDownload/CollectionDownloadView.axaml
  src/NexusMods.App.UI/Pages/CollectionDownload/CollectionDownloadView.axaml.cs
  src/NexusMods.App.UI/Pages/Diff/ApplyDiff/ApplyDiffView.axaml
  src/NexusMods.App.UI/Pages/ItemContentsFileTree/ItemContentsFileTreeView.axaml
  src/NexusMods.App.UI/Pages/LibraryPage/LibraryView.axaml
  src/NexusMods.App.UI/Pages/LibraryPage/LibraryView.axaml.cs
  src/NexusMods.App.UI/Pages/LoadoutPage/CollectionLoadoutView.axaml
  src/NexusMods.App.UI/Pages/LoadoutPage/LoadoutView.axaml
  src/NexusMods.App.UI/Pages/Sorting/LoadOrder/LoadOrderView.axaml
  src/NexusMods.App.UI/Pages/TextEdit/TextEditorPageView.axaml
  src/NexusMods.App.UI/Resources/Language.Designer.cs
  src/NexusMods.App.UI/Resources/Language.resx
  src/Themes/NexusMods.Themes.NexusFluentDark/Resources/ControlThemes/SplitButton.axaml
  src/Themes/NexusMods.Themes.NexusFluentDark/Resources/Palette/Colors/ElementColors.axaml
  src/Themes/NexusMods.Themes.NexusFluentDark/Resources/Palette/Gradients.axaml
  src/Themes/NexusMods.Themes.NexusFluentDark/Resources/ResourceIndex.axaml
  src/Themes/NexusMods.Themes.NexusFluentDark/Styles/Controls/Border/Toolbar.xaml
  src/Themes/NexusMods.Themes.NexusFluentDark/Styles/Controls/Button/StandardButtonStyles.axaml
  src/Themes/NexusMods.Themes.NexusFluentDark/Styles/Controls/SplitButton/SplitButtonStyles.axaml
  src/Themes/NexusMods.Themes.NexusFluentDark/Styles/Controls/TreeDataGrid/TreeDataGridLibraryStyles.axaml
  src/Themes/NexusMods.Themes.NexusFluentDark/Styles/StylesIndex.axaml
  src/Themes/NexusMods.Themes.NexusFluentDark/Styles/UserControls/CollectionDownloadPage/CollectionDownloadPageStyles.axaml
  src/Themes/NexusMods.Themes.NexusFluentDark/Styles/UserControls/CollectionLoadoutPage/CollectionLoadoutPageStyles.axaml
Labels: Dev UI

#2731 Styling workaround for Success Rating
  src/NexusMods.App.UI/Pages/CollectionDownload/CollectionDownloadView.axaml
  src/NexusMods.App.UI/Pages/CollectionDownload/CollectionDownloadView.axaml.cs
  src/NexusMods.App.UI/Pages/LibraryPage/Collections/CollectionCardView.axaml.cs
  src/Themes/NexusMods.Themes.NexusFluentDark/Styles/UserControls/CollectionCards/CollectionCardStyles.axaml
  src/Themes/NexusMods.Themes.NexusFluentDark/Styles/UserControls/CollectionDownloadPage/CollectionDownloadPageStyles.axaml
Labels: Dev UI
