Repository Nexus-Mods/NexusMods.App, pull requests merged in 2025-04, with the labels that each got.

#2970 Added changelog
  CHANGELOG.md
  docs/changelog-assets/b9eba6bd73a0421b9a9c0e017db10d50.webp
Labels: Documentation

#3000 Added 0.9.2 changelog
  CHANGELOG.md
Labels: Documentation

#3001 Grammar fixes
  CHANGELOG.md
Labels: Documentation

#3008 Uncommented warning for unsupported games.
  docs/users/games/index.md
Labels: Documentation

#3049 Add empty state for when collection has no required downloads
  src/NexusMods.App.UI/Pages/CollectionDownload/CollectionDownloadView.axaml
  src/NexusMods.App.UI/Pages/CollectionDownload/CollectionDownloadView.axaml.cs
Labels: Needs QA

#3028 Changelog v0.10
  CHANGELOG.md
  docs/changelog-assets/80c1fdba8263069e9bbe9f640dca8b31.webp
  docs/users/games/Cyberpunk2077.md
  docs/users/games/index.md
  docs/users/images/0.10.2/Cyberpunk2077LoadOrder.webp
  docs/users/images/0.7.1/Cyberpunk2077LoadOrder.webp
  docs/users/images/game-art/baldursgate3.webp
  docs/users/images/game-art/bannerlord.webp
  docs/users/images/game-art/cyberpunk2077.webp
  docs/users/images/game-art/stardewvalley.webp
Labels: Documentation

#3115 Cyberpunk 2077 health check
  src/NexusMods.Games.Generic/WineDiagnosticHelper.cs
  src/NexusMods.Games.RedEngine/Constants.cs
  src/NexusMods.Games.RedEngine/Cyberpunk2077/Diagnostics.cs
  src/NexusMods.Games.RedEngine/Cyberpunk2077/Emitters/MissingProtontricksForRedModEmitter.cs
  src/NexusMods.Games.RedEngine/Cyberpunk2077/Emitters/MissingRedModEmitter.cs
  src/NexusMods.Games.RedEngine/Cyberpunk2077/Emitters/PatternDefinitions.cs
Labels: Epic: Health Check
