Repository Nexus-Mods/NexusMods.App, pull requests merged in 2025-05, with the labels that each got.

#3177 Commented out Epic Games detection for CP2077 and Bannerlord
  src/NexusMods.Games.MountAndBlade2Bannerlord/Bannerlord.cs
  src/NexusMods.Games.RedEngine/Cyberpunk2077/Cyberpunk2077Game.cs
Labels: Epic: Game Support, Game: Cyberpunk 2077, Game: Bannerlord

#3194 Fix for no apply button
  src/NexusMods.Abstractions.Loadouts.Synchronizers/ALoadoutSynchronizer.cs
  src/NexusMods.Abstractions.Loadouts.Synchronizers/ILoadoutSynchronizer.cs
  src/NexusMods.Abstractions.Loadouts.Synchronizers/Rules/ActionMapping.cs
  src/NexusMods.DataModel/CommandLine/Verbs/LoadoutManagementVerbs.cs
  src/NexusMods.DataModel/Synchronizer/SynchronizerService.cs
Labels: backport candidate

#3193 More http download fixes
  src/NexusMods.Collections/CollectionDownloader.cs
  src/NexusMods.Collections/DownloadCollectionJob.cs
  src/NexusMods.Collections/DownloadSettings.cs
  src/NexusMods.Collections/Services.cs
  src/NexusMods.Networking.HttpDownloader/HttpDownloadJob.cs
  src/NexusMods.Networking.HttpDownloader/Services.cs
  src/NexusMods.Networking.NexusWebApi/ExternalDownloadJob.cs
Labels: backport candidate

#3212 Updated docs for 0.11
  docs/users/faq/LinuxProtocolRegistration.md
  docs/users/faq/NexusModsDownloads.md
  docs/users/games/Cyberpunk2077.md
  docs/users/games/StardewValley.md
  docs/users/gettingstarted/MovingToTheApp.md
  docs/users/images/0.10.2/Cyberpunk2077LoadOrder.webp
  docs/users/images/0.11.1/Cyberpunk2077LoadOrder.webp
  docs/users/images/0.11.1/HealthCheckExampleCyberpunk.webp
  docs/users/images/0.11.1/HealthCheckExampleSDV.webp
  docs/users/images/0.6.0/HealthCheckExampleCyberpunk.webp
  docs/users/images/0.7.2/HealthCheckExampleSDV.webp
  mkdocs.yml
Labels: Documentation

#3224 Fix the redmod deploy order
  src/NexusMods.Abstractions.Games/RunGameTool.cs
  src/NexusMods.Abstractions.Loadouts/Models/DiskStateExtensions.cs
  src/NexusMods.Games.RedEngine/Cyberpunk2077/RunCyberpunk2077Game.cs
  src/NexusMods.Games.RedEngine/RedModDeployTool.cs
  src/NexusMods.Games.RedEngine/Resources/Cyberpunk2077/deploy_redmod.bat
  src/NexusMods.Games.RedEngine/Services.cs
Labels: backport candidate

#3230 Changelog 0.11.3
  CHANGELOG.md
Labels: Documentation

#3243 Merge translation PRs
  src/NexusMods.App.UI/NexusMods.App.UI.csproj
  src/NexusMods.App.UI/Resources/Language.pt-BR.resx
  src/NexusMods.App.UI/Resources/Language.ru.resx
  src/NexusMods.App.UI/Resources/Language.uk.resx
  src/NexusMods.App.UI/Settings/LanguageSettings.cs
  src/NexusMods.Games.AdvancedInstaller.UI/NexusMods.Games.AdvancedInstaller.UI.csproj
  src/NexusMods.Games.AdvancedInstaller.UI/Resources/Language.pt-BR.resx
  src/NexusMods.Games.AdvancedInstaller.UI/Resources/Language.ru.resx
  src/NexusMods.Games.AdvancedInstaller.UI/Resources/Language.uk.resx
  src/NexusMods.Games.FOMOD.UI/NexusMods.Games.FOMOD.UI.csproj
  src/NexusMods.Games.FOMOD.UI/Resources/Language.pt-BR.resx
  src/NexusMods.Games.FOMOD.UI/Resources/Language.ru.resx
  src/NexusMods.Games.FOMOD.UI/Resources/Language.uk.resx
Labels: translation
