Repository Nexus-Mods/NexusMods.App, pull requests merged in 2025-03, with the labels that each got.

#2751 Docs 074
  docs/users/features/ExternalChanges.md
  docs/users/gettingstarted/index.md
  docs/users/images/0.7.4/ExternalChanges.webp
  docs/users/images/SteamDeckMenu.webp
  docs/users/images/SteamDeckPropertiesPermissions.webp
  mkdocs.yml
Labels: Documentation

#2792 Update UndeployableLoadoutDueToMissingGameFiles diagnostic
  src/NexusMods.Games.FileHashes/Diagnostics.cs
  src/NexusMods.Games.FileHashes/Emitters/UndeployableLoadoutDueToMissingGameFiles.cs
Labels: Epic: Health Check

#2828 Add special Toggle states and behaviours for parent items in Loadout and Collection Views
  src/NexusMods.App.UI/Controls/TreeDataGrid/CompositeItemModel.cs
  src/NexusMods.App.UI/Controls/TreeDataGrid/TreeDataGridItemModel.cs
  src/NexusMods.App.UI/Converters/IsNotNullConverter.cs
  src/NexusMods.App.UI/Converters/IsNullConverter.cs
  src/NexusMods.App.UI/Pages/BundledDataProvider.cs
  src/NexusMods.App.UI/Pages/CollectionDownload/CollectionComponents.cs
  src/NexusMods.App.UI/Pages/ILoadoutDataProvider.cs
  src/NexusMods.App.UI/Pages/LoadoutPage/CollectionLoadoutViewModel.cs
  src/NexusMods.App.UI/Pages/LoadoutPage/LoadoutComponents.cs
  src/NexusMods.App.UI/Pages/LoadoutPage/LoadoutViewModel.cs
  src/NexusMods.App.UI/Pages/LoadoutPage/TreeDataGridLoadoutResources.axaml
  src/NexusMods.App.UI/Pages/LocalFileDataProvider.cs
  src/NexusMods.App.UI/Pages/NexusModsDataProvider.cs
  src/Themes/NexusMods.Themes.NexusFluentDark/Styles/Controls/TreeDataGrid/TreeDataGridActionsColumnStyles.axaml
  src/Themes/NexusMods.Themes.NexusFluentDark/Styles/StylesIndex.axaml
Labels: Design UI/UX

#2774 Tidy up the GitHub templates
  .github/ISSUE_TEMPLATE/01-bug.md
  .github/ISSUE_TEMPLATE/02-feature.md
  .github/ISSUE_TEMPLATE/03-reportmissinggame.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/epic.md
  .github/ISSUE_TEMPLATE/improvement.md
  .github/ISSUE_TEMPLATE/spike.md
Labels: Documentation

#2884 Added a linebreak as the new image is smaller.
  docs/users/faq/LogFiles.md
Labels: Documentation

#2830 Update Strawberry Shake (GraphQL Client)
  Directory.Packages.props
Labels: priority-low

#2924 Changelog 0.8.3
  CHANGELOG.md
  docs/changelog-assets/2264297d178012ec96f139ffd5ea79aa.webp
Labels: Documentation

#2927 Added important note to the changelog
  CHANGELOG.md
Labels: Documentation
